### ISSUE TITLE
Take a 1000x1000 matrix with its dimensions as input from file

### ISSUE THREAD

**Issue by sandy9999** [ladnir/aby3#10]
Hi, I'm looking to run the Sh3_Evaluator_asyncMul_test() from Sh3EvaluatorTest.cpp by taking the dimensions of the matrix, and then the actual matrix as input from a file. How do I go about this?

**Comment by ladnir** [comment]
Are the matrices already secret shared? If yes it's a bit more complicated. 

Otherwise if each party has a matrix. Then you load the file into a plaintext matrix. Then you use the encryptor to generate secret shares and multiply them.

**Comment by sandy9999** [comment]
The matrices are already secret shared, yes but maybe I'll ask you that after understanding the simpler case.

We usually run the test using ./bin/frontend.exe -u <test_no> with some extra arguments to take single values as input. How do I take the entire plain matrix as input from a file in ./bin/frontend.exe so that the matrix ends up being an argument in the test? Would the traditional fstream, freopen methods work or do you have an aby3 specific method to do it?

If there's a code example of where this sort of thing is being done, kindly direct me there.

**Comment by ladnir** [comment]
There is no preferred method for file IO. Use your favorite. Read the file into a plaintext matrix. Up to you how to do this should be extremely simple. Then use the encryptor to encrypt/secret share each.

What type of secret sharing are you starting with?

**Comment by sandy9999** [comment]
Ah I'll do that, thank you so much for your response. I'm using a slightly tweaked version of what's already there in the repository, so we can consider that it's the same aby3 arithmetic and binary sharing schemes.

So suppose I consider [[ x ]] = (x1, x2, x3) , maybe I could pass (x1, x2, x3) as arguments and make P0 keep x1, x2 , and distribute x2, x3 to P1 and x1, x3 to P2? Would it still preserve the secrecy of the computation?
