### ISSUE TITLE
Working with fixed point type

### ISSUE THREAD

**Issue by sandy9999** [ladnir/aby3#12]
I'm trying to work with shares that are floats/doubles as it seemed most appropriate. 

I declared a variable fixedInt of type f64<D8> as follows:

`f64<D8> fixedInt = 34.124`

When I print the value of this variable using std::cout, I get

`34.12109375`

It's not even a rounding error. I don't quite understand why the value printed is so far from intended.

Also, is `f64<D8> fixedInt = 2/double(3)` the right way to store 0.6666667 in fixedInt? When I print fixedInt after doing this, it prints 0.6640625 (Similar issue as above)

**Comment by sach123san** [comment]
why sandy.
i have no problem what you had done to me.
  but i can't leave with such allegtions.
give me any punishment but speaks the truth.

**Comment by sach123san** [comment]
i am not strong like you, sensitive& emotional. never went out of my village.for what you had given me such punishment.

**Comment by ladnir** [comment]
I suspect it's just a rounding error from having only 8 bit decimal. Try increasing it. For example, use D32.

**Comment by sandy9999** [comment]
I tried changing it to D32, and got `34.12399999983608722686767578125` as my output. It's closer, but is there any way to get the exact value?

**Comment by ladnir** [comment]
So, in general, not all values can be represented in base 2. However, it appears 0.124 can be. The way the conversion is implemented is shown here https://github.com/ladnir/aby3/blob/master/aby3/sh3/Sh3FixedPoint.h#L89

So, what that means is
```cpp
f64<D32> fixedInt1 = 34.124; 
// same as
f64<D32> fixedInt2;
finxedInt2.mValue = double(34.124) * (i64(1) << 32);
```
Therefore, if you want some other conversion method, then you can just implement it in a similar way.

**Comment by sandyyyy99** [comment]
whats my mistake,I was dealing with loneliness so texted you. texts were desgusting then you may told me, I may had stopped.
i was dealing with depression & under medication from last 6 years.Everyone of my friends knows that.I belongs from small village, I can't have nature as per you.It's my habit to speaks bad words,everytime i will.Even my dad starts his conversation with bad words,but everyone in sikar likes him bc he will do lot to help poor persons, he have kind heart. In roopa case, roopa used to text lot of persons, like she loves them how can I have attachment.
why sandyyyyy....
okk I am worst person but you had given me death sentence,sandyy.I can't sleep at night

**Comment by sandyyyy99** [comment]
if I die then my parents may not be able to leave.If you ask in entire sikar, you will hear, my parents are nicest person they know.My dad speaks bad words every min. but thousands & thousands loves him. 
you may have judged me after talking to my friends, I am depressed & anxiety issues so I can't able to talk &think  properly but they have very good nature.I am depressed & lonliness issue bc no friend in nitt.if you talk to suyash,nabh,etc,etc you may realise how good they are.

**Comment by sandyyyy99** [comment]
if a person awkward behaviour, he may be dealing with some issues. rather than helping me you made it complicated.I am not such kind of person who have hatred issue but almost made me suicide.karma is something which always strike back.anyway am not gonna do anything to you.

**Comment by sandyyyy99** [comment]
TELL exact TRUTH TO YOUR PARENTS & ASK THEM WHAT YOU DID IS RIGHT OR WRONG. DEFINETLY YOU WILL BE WRONG.SOMETIME SOMEONE MAY BE GOING THROUGH TOUGH PHASE IN LIFE.tell you should help or make life complicated.

**Comment by sandyyyy99** [comment]
you are good girl sandhya like my friends praggya, divya,etc,etc...
 I know whatever I did , way I behave is not good.but all thesse was unknowingly.depression extent-I was not in state to talk to people.but everything was fine after completing my degree.

**Comment by sandyyyy99** [comment]
at night I can't able to breathe.
 you made my mentally died.
 that was SANDY'S..... LOVE.

**Comment by sandyyyy99** [comment]
I MAY BE WORST,CHARATERLESS, ETC,etc...... but I never killed person like you.

**Comment by sandyyyy99** [comment]
byee....

**Comment by ladnir** [comment]
wish you luck. Things can be hard but it's important to keep on trying.

**Comment by sach1sandy99** [comment]
tell me what was my mistake.
 i never approached you, stalked you.I had not told to come to me.okk I was depressed & have anxiety issues so definitely my text will be disgusting &irritating one.But you talked to my friends, you should have judged from there.ST Ramesh was reason for depression.you made me have suicidal thoughts , I may had killed myself.okk I speaks bad words but that don't show me.

**Comment by sach1sandy99** [comment]
okk you hates me , as per u I have worst nature , yeap I am very very bad person then you should have told me to not to text you I may had stopped.your are source to overcome my loneliness.
you almost made me suicide.
 i already gone through very tough phase in life.

**Comment by sach1sandy99** [comment]
hey you may be very very good but you fucked my life.I may cracked upsc within these 2 years.think what you have done. If I want I may had used you but did nothing you should know that.

**Comment by sach1sandy99** [comment]
ask kamalesh, I can't able to sleep at night, I will make 50-60 calls daily. anyway he is very good person so tolerate me.
atleast speak the truth , this allegation hurts me.

**Comment by sach1sandy99** [comment]
please allow me to text you, I don't  want more efforts to make accounts.please......
 please bear myy stupidity.
I feel relaxed after texting you, please.after making my life complicated, pleae help me. I have no hatred for you sandyyy.
 don't remove comment section.

**Comment by sach1sandy99** [comment]
you can ignore them , I feel good to text you, please. If you want give me any punishment but allow me text.
Don't remove comment section.

**Comment by sach1sandy99** [comment]
give me some time to forget you'.

**Comment by sach1sandy99** [comment]
promise slowli slowly I will go away from you, Give me time to forget you,please bear bakchodi for sometime.

**Comment by sach1sandy99** [comment]
u made me suffer lot, can't you suffers my texts please.don't remove comment section.

**Comment by sach1sandy99** [comment]
i can't make more account mhe toh vese hi bahut bola hu.

**Comment by sach1sandy99** [comment]
you made me to die sandy....what was my mistake.

**Comment by sach1sandy99** [comment]
almost made me suicide...
 you made life lead with anxiety.

**Comment by sach1sandy99** [comment]
bc can't able to sleep.

**Comment by sach1sandy99** [comment]
chal am chararterless, disgusting, etc,etc but bc am not murder like sandhya.

**Comment by sach1sandy99** [comment]
kitna bola hu , bolapan toh dekh leti..

**Comment by sach1sandy99** [comment]
entire life spoil kar di

**Comment by sach1sandy99** [comment]
tell me how to forget you bc body vibrate karti rahti ha. bc yaad toh aahigi na.

**Comment by sach1sandy99** [comment]
i had not told to come to my life, you were free to leave, just source to overcome loneliness if you had told me to stop I may had done that but now got attached to memory so really tough to forget.
mentally died....

**Comment by sach1sandy99** [comment]
no one spoil life like what you have done..

**Comment by sach1sandy99** [comment]
suicide note mhe tera name likh ki marunga.
