### ISSUE TITLE
compling error with gcc 5.5.0 and gcc 5.4.0

### ISSUE THREAD

**Issue by 4aimar** [ladnir/aby3#13]
Hi guys,

I compiled aby3 and got the following issue. 

aby3/aby3-DB/LowMC.h:45:53: error: array must be initialized with a brace-enclosed initializer

built successfully after changing the code snippets ( in aby3/aby3-DB/LowMC.h)
From:
const std::array<u8, 8> Sbox =
            { 0x00, 0x01, 0x03, 0x06, 0x07, 0x04, 0x05, 0x02 };
            const std::array<u8, 8> invSbox =
            { 0x00, 0x01, 0x07, 0x02, 0x05, 0x06, 0x03, 0x04 };
To:
const std::array<u8, 8> Sbox =
            {{ 0x00, 0x01, 0x03, 0x06, 0x07, 0x04, 0x05, 0x02 }};
            const std::array<u8, 8> invSbox =
            {{ 0x00, 0x01, 0x07, 0x02, 0x05, 0x06, 0x03, 0x04 }};

refering to the two following links
https://stackoverflow.com/questions/26161373/how-to-initialize-stdarray-in-class-definition
https://stackoverflow.com/questions/8192185/using-stdarray-with-initialization-lists

**Comment by ladnir** [comment]
fixed.
