### ISSUE TITLE
circuitInputShare's content are not from cuckooTable

### ISSUE THREAD

**Issue by 4aimar** [ladnir/aby3#14]
A = [1,2,3,4,5,6]  B = [1,2,3,10,11,12] do DB_Intersection
After revealing the cuckooTable and circuitInputShare table found:

cuckooTable was right:
cucktable[11] =	0a000000000000000a00241e97865ed3b56c64e6a8e9d682c30019dc8880ad289a74
cucktable[12] =	01000000000000000100297937b4b86ca021327c02488fa0df20bbafef6f33556e86
ccuktable[18] =	0c000000000000000c00186fc64c5c5681abfc6b7bd62111722317ac91052710215c
cucktable[20] =	03000000000000000300677c7b5348bdede1a8cac793598768fec6481f67eccf8a18
cucktable[23] =	02000000000000000200d0ff93f69f0aef062dc171f7f94ee6677b42301fa9e48cca
cucktable[24] =	0b000000000000000b00ef8912f6ede93b3d5772bbaa9683a39b62d9c6eeb2a5d6a8

**But hash table was wrong: only one line in hash0 could match the data of cuckootable. This is a bug, you could reproduce in the latest version easily** 

**hash0 = 01000000000000000100297937b4b86ca021327c02488fa0df20bbafef6f33556e86**
hash0 = 5ec72263a4b84a31fd447fc2792ab70f2bd6864cd270530518387a637d08ef35ab7b
hash0 = b72863843fa22c17f48f84380ff92a09b8951ce58e07862edea2e7603c9f2cad2d4a
hash0 = 030000005b366cb37eb581a652d4b32a38103c6e84c4ae7cb30e24bd525e8bcb3eeb 
hash0 = daa841e0643a427095af276396941f308b9b5d585396fa096e22c36bb1039754a4de
hash0 = 13decd5f80a00cdbde86f8c332c0fe7e58f3b51c96afb10c93eee012c85ac53d081a 

hash1 = 13decd5f80a00cdbde86f8c332c0fe7e58f3b51c96afb10c93eee012c85ac53d081a
hash1 = 00000000000000000000000000000000000000000000000000000000000000000000
hash1 = 5cc72263a4b84a31ff44af3deadc2805c4d0ab8da387aa4bfe5f01214d1746d127b1
hash1 = c9768cbfe49a4eab4b29dfa0a454e14ed368e844c5394b05fdcc237979595269acc4
hash1 = 000000005b366cb37db5e6da2987fb97d5f194a44357f7fbdbf0e2f54d396704b4f3
hash1 = b4286384649440a48a3a059e5d2d99238085208b0ac328526dacc3dd6ec1a76613a1

hash2 = b4286384649440a48a3a059e5d2d99238085208b0ac328526dacc3dd6ec1a76613a1
hash2 = 000000005b366cb37db5e6da2987fb97d5f194a44357f7fbdbf0e2f54d396704b4f3
hash2 = 5cc72263a4b84a31ff44af3deadc2805c4d0ab8da387aa4bfe5f01214d1746d127b1
hash2 = c9768cbfe49a4eab4b29dfa0a454e14ed368e844c5394b05fdcc237979595269acc4
hash2 = 13decd5f80a00cdbde86f8c332c0fe7e58f3b51c96afb10c93eee012c85ac53d081a
hash2 = 00000000000000000000000000000000000000000000000000000000000000000000

**Comment by 4aimar** [comment]
Seems there was something wrong with the Duplication Network. I constructed two unsafe duplication functions for P1 and P2 to replace programDuplicate(), sendDuplicate(), helpDuplicate() and everything goes well.

**Comment by ladnir** [comment]
Could you be more specific, maybe provide a minimum working example. All the code is unit tested so it should work for the most part...

**Comment by ladnir** [comment]
Maybe you can tell me what you want to achieve and I can give you some pointers on how the code works.

**Comment by 4aimar** [comment]
What I tested was running the test case "DB_Intersect_test(6, 6)" but the test result was failure with the latest source code. 
These were the steps I did:

1. printed P0's and P1's key generated by computeKeys(), found the first three values of A and B had the same hash values, proved that the lowMC was correct.

2. revealed "Matrix < u8 > cuckooTable" generated by P0, P1 and P2, found all the set B's values could be found from cuckooTable, proved that permutation network was correct.

3. revealed "std::array<Matrix < u8 >, 3> circuitInputShare" generated by P0, P1 and P2, found only the first column of circuitInputShare[0] could match the cuckooTable. --> "stated in the first post"

	So I guess maybe something wrong in duplication network. 
	What I did was:

- 1) wrote two functions:

			        void OblvSwitchNet::getPAI2P1(
						Channel & sendrChl,
						Channel & helperChl,
						Program& prog,
						PRNG& prng,
						MatrixView<u8> dest) {
					PRNG otPrng(toBlock(345345));

					auto rows = dest.rows();
					std::vector<u8> bits((rows + 6) / 8);
					otPrng.get(bits.data(), bits.size());

					BitIterator iter(bits.data(), 0);
					{
						for (u32 i = 1; i < rows; ++i)
						{
							bool dup = (prog.mSrcDests[i - 1].mSrc == prog.mSrcDests[i].mSrc);
							*iter = dup;
							++iter;
						}
					}
					sendrChl.asyncSend(bits);

					std::this_thread::sleep_for(std::chrono::microseconds(20));

					for (u32 i = 1; i < rows; ++i)
					{
						bool dup = (prog.mSrcDests[i - 1].mSrc == prog.mSrcDests[i].mSrc);

						if (dup) {
							auto destPtr = &dest(i, 0);
							auto srcPtr = &dest(i - 1, 0);
							memcpy(destPtr, srcPtr, dest.stride() * 1);
						}
					}          
				}
				
			        void OblvSwitchNet::getPAI2P2(Channel & programChl, PRNG& prng, MatrixView<u8> src)
				{
					auto rows = src.rows();
					PRNG otPrng2(toBlock(645687456));
					std::vector<u8> sendData((rows - 1) * src.stride() * 2);
					otPrng2.get(sendData.data(), sendData.size());
					
					std::vector<u8> bits((rows + 6) / 8);
					BitIterator iter(bits.data(), 0);
					programChl.recv(bits.data(), bits.size());

					for (u32 i = 1; i < rows; ++i)
					{
						if (*iter) {
							auto destPtr = &src(i, 0);
							auto srcPtr = &src(i - 1, 0);
							memcpy(destPtr, srcPtr, src.stride() * 1);
						}
						++iter;
					} 
				}
	

- 2) commented the three functions programDuplicate(), sendDuplicate(), helpDuplicate()

 

			1) and use "getPAI2P1" to replace programDuplication() 
			
			//programDuplicate(helpChl, sendrChl, prog, prng, temp);
			getPAI2P1(helpChl, sendrChl, prog, prng, temp);
			
			2) use "getPAI2P2" to replace "sendDuplicate()"
			
			//sendDuplicate(programChl, prng, temp);
			getPAI2P2(programChl, prng, temp);
			
		

- 3) the test case could run successfully.

**Comment by ladnir** [comment]
So, is a test failing when you run them with **no modifications**? Or did you change something and now the test is failing.

Are you simply trying to get an understanding of what is happening in these functions or are you wanting to modify them?

If you want, I can tell you the state of the data at each step.

It is still unclear to me what you want me to do.

**Comment by ladnir** [comment]
ok, i ran the tests and also getting a failure. The source of the bug is an update to cryptoTools/libOTe. I will fix this.

FYI, all you had to say in the issue is that: "I cloned the repo and ran the unit tests. The test `DB_Intersect_test` is failing with output `....`."

**Comment by ladnir** [comment]
fixed. Please pull aby3, libOTe/cryptoTools.

**Comment by 4aimar** [comment]
Thanks for the update.  Pull the new repos aby3 and libOTe/cryptoTools, it works.
