### ISSUE TITLE
how to convert sbMatrix to si64Matrix? 

### ISSUE THREAD

**Issue by 4aimar** [ladnir/aby3#15]
Hello,

Can a matrix with the type of **sbMatrix** add each row and get a result? Seems the following code can't work.

```
auto select = std::vector<SharedTable::ColRef>{ B["key"], B["b1"], B["b2"], A["key"], A["a1"], A["a2"]};
auto C = srvs[i].leftJoin(A["key"], B["key"], select, "registed");

aby3::sbMatrix& b1Col = C.mColumns[1];
aby3::sbMatrix b1Sum(b1Col.rows(), b1Col.i64Cols());
b1Sum.mShares[0].setZero();
b1Sum.mShares[1].setZero();

// b1Sum add each row
for (u64 j = 0; j < b1Col.rows(); ++j) {
		b1Sum.mShares[0](0) += b1Col.mShares[0](j);
		b1Sum.mShares[0](1) += b1Col.mShares[1](j);
}
```

I find si64Matrix could do the plus and mul operation. **So how can I  convert sbMatrix to si64Matrix**?  Thanks.

**Comment by ladnir** [comment]
this is not implemented as of now. `sbMatrix` is a binary secret shared matrix. So you can't add the shares to get the result, you xor them.

if needed, at some point i could implement this. The way you would convert is to input the `sbMatrix` into a binary circuit which converts them into an additive sharing. ie
```
conv(x1,x2,x3):
    x = x1^ x2^x3;
    y1 = random()
    y2 = random()
    y3 = x - y1 - y3
    output (y1,y2), (y2,y3), (y3,y1)  to P1,P2,P3 respectively.
```

To actually implement this, you could have the corresponding parties input `y1,y2` and only output `y3` to P2,P3.

If you implement this, feel free to make a PR. There is already a function signature for this in the `Sh3Converter` class.

**Comment by 4aimar** [comment]
Thanks for the response. 
I analyed localInput(), remoteInpt()  and found the samples in the DBServerTests.cpp, the thread 0 acts P0 using srvs[0], and has two sets A, B in local. If I want P0 owns A, P1 owns B, this servs initialized by the following code can't meet this requirement, right?

```
    IOService ios;
    Session s01(ios, "127.0.0.1", SessionMode::Server, "01");
    Session s10(ios, "127.0.0.1", SessionMode::Client, "01");
    Session s02(ios, "127.0.0.1", SessionMode::Server, "02");
    Session s20(ios, "127.0.0.1", SessionMode::Client, "02");
    Session s12(ios, "127.0.0.1", SessionMode::Server, "12");
    Session s21(ios, "127.0.0.1", SessionMode::Client, "12");


    PRNG prng(OneBlock);
    DBServer srvs[3];
    srvs[0].init(0, s02, s01, prng);
    srvs[1].init(1, s10, s12, prng);
    srvs[2].init(2, s21, s20, prng);
```

**Comment by 4aimar** [comment]
> Thanks for the response.
> I analyed localInput(), remoteInpt() and found the samples in the DBServerTests.cpp, the thread 0 acts P0 using srvs[0], and has two sets A, B in local. If I want P0 owns A, P1 owns B, this servs initialized by the following code can't meet this requirement, right?
> 
> ```
>     IOService ios;
>     Session s01(ios, "127.0.0.1", SessionMode::Server, "01");
>     Session s10(ios, "127.0.0.1", SessionMode::Client, "01");
>     Session s02(ios, "127.0.0.1", SessionMode::Server, "02");
>     Session s20(ios, "127.0.0.1", SessionMode::Client, "02");
>     Session s12(ios, "127.0.0.1", SessionMode::Server, "12");
>     Session s21(ios, "127.0.0.1", SessionMode::Client, "12");
> 
> 
>     PRNG prng(OneBlock);
>     DBServer srvs[3];
>     srvs[0].init(0, s02, s01, prng);
>     srvs[1].init(1, s10, s12, prng);
>     srvs[2].init(2, s21, s20, prng);
> ```

I  know the answer now, thanks. 

the first process acts P0:
 

        IOService ios;
        Session s01(ios, "127.0.0.1", 1212, SessionMode::Server, "01");
        Session s02(ios, "127.0.0.1", 1213, SessionMode::Client, "02");
        PRNG prng(oc::ZeroBlock);
        DBServer srvs[3];
        srvs[0].init(0, s02, s01, prng);

        Table a(rows, aCols);
        auto A = srvs[i].localInput(a);
        auto B = srvs[i].remoteInput(1);

		
the second process acts P1:		

        IOService ios;
        Session s10(ios, "127.0.0.1", 1212, SessionMode::Client, "01");
        Session s12(ios, "127.0.0.1", 1214, SessionMode::Server, "12");
        PRNG prng(oc::ZeroBlock);
        DBServer srvs[3];
        srvs[1].init(1, s10, s12, prng);
	
        Table b(rows, bCols);
        auto A = srvs[i].remoteInput(0);
        auto B = srvs[i].localInput(b);

		
the third process acts P2:			

        IOService ios;
        Session s20(ios, "127.0.0.1", 1213, SessionMode::Server, "02");
        Session s21(ios, "127.0.0.1", 1214, SessionMode::Client, "12");
        PRNG prng(oc::ZeroBlock);
        DBServer srvs[3];
        srvs[2].init(2, s21, s20, prng);
		
        auto A = srvs[i].remoteInput(0);
        auto B = srvs[i].remoteInput(1);

**Comment by ladnir** [comment]
exactly.
