### ISSUE TITLE
boost error

### ISSUE THREAD

**Issue by hros** [ladnir/aby3#16]
following the Linux installation notes on Ubuntu 20.04 fails on the next to last line (`cmake .`) with the following error message:
```
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find Boost: missing: system thread (found /home/user/boost/lib/cmake/Boost-1.74.0/BoostConfig.cmake (found version "1.74.0"))
CMake Error at aby3/CMakeLists.txt:19 (message):
  Failed to find boost at Need system thread


-- Configuring incomplete, errors occurred!
See also "/home/user/Projects/ABY3/aby3/CMakeFiles/CMakeOutput.log".
```

**Comment by ladnir** [comment]
pull aby3, libOTe and cryptoTools.  Rebuild the and it should be fixed.

**Comment by ladnir** [comment]
make sure you have boost installed somwhere. Or you can get its path manually via `cmake . -DBOOST_ROOT=path/to/boost`

**Comment by hros** [comment]
thanks Peter (or perhaps you prefer retep on github ;))
I added the `-DBOOST_ROOT` argument to both `cmake .` lines in the instructions and it compiled correctly
I thought that the line `bash boost.get` downloads and uses the appropriate version of boost, and so it is not necessary to point to my installed version
btw, the instructions suggest running `./bin/frontend` which is not generated. running `make` in the `frontend` directory produces `frontend.exe` on Linux, and running the tests (with the `-u` command line argument) results in all but one passing.
The failed test is:
`aby3-DB_tests/lowMC.cpp:313 `

**Comment by ladnir** [comment]
yeah, I'm in the process of updating the cmake system and haven't finished everything. Thanks for pointing these out.

**Comment by ladnir** [comment]
if you repull libOTe/cryptoTools, it should hopefully find boost correctly.
