### ISSUE TITLE
How to implementation more than 3 parties 

### ISSUE THREAD

**Issue by xbkaishui** [ladnir/aby3#18]
I have a question about current implementation, currently only support 3 parties , how to add more than 3 parties ? 
thanks

**Comment by ladnir** [comment]
well...

this is non-trivial depending on what exactly you want. Some of the protocols do not generalize in any trivial way. What exactly do you want to do?

**Comment by xbkaishui** [comment]
Thanks for you reply. I want support more than 3 parties to use Arithmetic and Binary evaluator to calc  ADD MUL AND GreateThan logic. is that possible ?

**Comment by ladnir** [comment]
yeah, it can be generalized but it's somewhat non-trivial. The basic idea of replicated secret sharing does generalize.

If you have n parties, and t=(n-1)/2 are corrupt then:
- there are m= (n choose {n-t}) shares (arithmetic or binary). 
- You define the m subsets D1,...,Dm\in {1,2,...,n}, such that each subset Dj is distinct and of size n-t.  These sets are unique.
- Each party i\in Dj will hold share xj. Therefore you will have x = x1+x2+...+xm.
- Addition is just adding the local shares
- multiplication is having the parties locally multiplying the cross-terms, masking that by a zero share, and sending the resulting share to the corresponding parties.

For greater than, you can input the arithmetic shares into a binary-MPC, evaluate the reconstruction circuit and then evaluate the greater than circuit.

My suggestion is to simply start your own project and not directly add to this codebase. Feel free to use it as a starting point/example, but it'll likely be easiest that way.

cheers,
Peter

**Comment by xbkaishui** [comment]
Ok, got your point. I will try to implement the ABYN base on your great work. thanks
