### ISSUE TITLE
what the logic of matrix multiplication is in aby3?

### ISSUE THREAD

**Issue by lidh15** [ladnir/aby3#19]
Hi, I tried the matrix operation demo in frontend/aby3Tutorial.cpp where the matrix is with 10 rows and 4 columns.

I noticed that the multiplication got two matrix of 10X4 as input and output it to another place with the same shape. 

I think we can do 10X4 multiplies 4X10 to get a 10X10 or do 4X10 multiplies 10X4 to get a 4X4, but if we do 10X4 * 10 X4 we should receive an error in Eigen, right? I'm just wondering what happened in the matrix multiplication in the tutorial codes. 

Thank you

**Comment by ladnir** [comment]
The underlying matrix operations are performed by eigen so they should be correct.
