### ISSUE TITLE
How to config different ip when initing the Sessions

### ISSUE THREAD

**Issue by cyckun** [ladnir/aby3#20]
When i tring to cofig three ips for three parties in Sessions's init, the code is correctly compiled, but the logistic task run with segment fault error. P0 is (server, server) mode, P1 is (server, client) mode, P2 is (client, client) mode,  P0 is running on ip = 150.1; P1, and P2 are running on ip = 150.138.  
         if (i == 0) { ip_next = "0.0.0.0"; ip_prev = "0.0.0.0"; }
                else if (i == 1) { ip_next = "0.0.0.0"; ip_prev = "192.168.150.1"; }
                else if (i == 2) { ip_next = "192.168.150.1"; ip_prev = "192.168.150.138"; }
                else { std::cout << "ip config error. " << std::endl; }
Anyone has been trying ip config like this?, what's wrong is it?  Thanks.

**Comment by ladnir** [comment]
Looks like that should work in theory. Maybe first check that you can connect/ping those IPs. Try each pair of connections in isolation.
```
    IOService ios;
    Channel server = Session(ios, "0.0.0.0:1212", oc::SessionMode::Server).addChannel();
    Channel client = Session(ios, "127.0.0.1:1212", oc::SessionMode::Client).addChannel();

    std::cout << "connecting..." << std::endl;
    client.waitForConnection();
    server.waitForConnection();
    std::cout << "passed" << std::endl;
```
Change the IP address and port that the client is using appropriately.

**Comment by cyckun** [comment]
Hi ladnir, thanks your reply,  this question is solved. p0 is running as (server, server), ip_next should not 0.0.0.0, it should be 192.168.150.1. Thanks very much.

**Comment by cyckun** [comment]
closed

**Comment by cyckun** [comment]
close.
