### ISSUE TITLE
test 94 sometimes failed on ubuntu

### ISSUE THREAD

**Issue by liqi16** [ladnir/aby3#25]
simba@ubuntu:~/aby3$ bin/frontend -u
  0 - BtNetwork_SBO_ptr_test                    Passed   0ms
  1 - BtNetwork_Connect1_Test                   Passed   2ms
  2 - BtNetwork_RapidConnect_Test               Passed   69ms
  3 - BtNetwork_shutdown_test                   Passed   2ms
  4 - BtNetwork_SocketInterface_Test            Passed   12ms
  5 - BtNetwork_OneMegabyteSend_Test            Passed   3ms
  6 - BtNetwork_ConnectMany_Test                Passed   12ms
  7 - BtNetwork_CrossConnect_Test               Passed   2ms
  8 - BtNetwork_ManySessions_Test               Passed   20ms
  9 - BtNetwork_bitVector_Test                  Passed   0ms
 10 - BtNetwork_AsyncConnect_Test               Passed   5ms
 11 - BtNetwork_std_Containers_Test             Passed   0ms
 12 - BtNetwork_recvErrorHandler_Test           Passed   1ms
 13 - BtNetwork_closeOnError_Test               Passed   1ms
 14 - BtNetwork_AnonymousMode_Test              Passed   0ms
 15 - BtNetwork_CancelChannel_Test              Passed   142ms
 16 - BtNetwork_useAfterCancel_test             Passed   6ms
 17 - BtNetwork_fastCancel                      Passed   24ms
 18 - BtNetwork_ServerMode_Test                 Passed   31ms
 19 - BtNetwork_clientClose_Test                Passed   43ms
 20 - BtNetwork_BadConnect_Test                 Passed   0ms
 21 - BtNetwork_oneWorker_Test                  Passed   1ms
 22 - BtNetwork_queue_Test                      Passed   1ms
 23 - BtNetwork_socketAdapter_test              Passed   2ms
 24 - BtNetwork_BasicSocket_test                Passed   1ms
 25 - wolfSSL_echoServer_test                   Skipped - ENABLE_WOLFSSL not defined   0ms
 26 - wolfSSL_mutualAuth_test                   Skipped - ENABLE_WOLFSSL not defined   0ms
 27 - wolfSSL_channel_test                      Skipped - ENABLE_WOLFSSL not defined   0ms
 28 - wolfSSL_CancelChannel_Test                Skipped - ENABLE_WOLFSSL not defined   0ms
 29 - block_operation_test                      Passed   0ms
 30 - AES                                       Passed   0ms
 31 - Rijndael256                               Passed   0ms
 32 - BitVector_Indexing_Test                   Passed   0ms
 33 - BitVector_Parity                          Passed   2ms
 34 - BitVector_Append_Test                     Passed   0ms
 35 - BitVector_Copy_Test                       Passed   0ms
 36 - BitVector_Resize_Test                     Passed   0ms
 37 - CuckooIndex_many_Test                     Passed   15ms
 38 - CuckooIndex_paramSweep_Test               Passed   67ms
 39 - CuckooIndex_parallel_Test                 Passed   0ms
 40 - Ecc2mNumber_Test                          Skipped - ENABLE_MIRACL not defined.   0ms
 41 - Ecc2mPoint_Test                           Skipped - ENABLE_MIRACL not defined.   0ms
 42 - EccpNumber_Test                           Skipped - ENABLE_MIRACL not defined.   0ms
 43 - EccpPoint_Test                            Skipped - ENABLE_MIRACL not defined.   0ms
 44 - REccpNumber_Test                          Skipped - ENABLE_RELIC not defined.   0ms
 45 - REccpPoint_Test                           Skipped - ENABLE_RELIC not defined.   0ms
 46 - BetaCircuit_SequentialOp_Test             Passed   0ms
 47 - BetaCircuit_int_Adder_Test                Passed   0ms
 48 - BetaCircuit_int_Adder_const_Test          Passed   2ms
 49 - BetaCircuit_int_Subtractor_Test           Passed   10ms
 50 - BetaCircuit_int_Subtractor_const_Test     Passed   4ms
 51 - BetaCircuit_uint_Adder_Test               Passed   4ms
 52 - BetaCircuit_uint_Subtractor_Test          Passed   3ms
 53 - BetaCircuit_int_Multiply_Test             Passed   0ms
 54 - BetaCircuit_uint_Multiply_Test            Passed   1ms
 55 - BetaCircuit_int_Divide_Test               Passed   3ms
 56 - BetaCircuit_int_LessThan_Test             Passed   0ms
 57 - BetaCircuit_int_GreaterThanEq_Test        Passed   0ms
 58 - BetaCircuit_uint_LessThan_Test            Passed   1ms
 59 - BetaCircuit_uint_GreaterThanEq_Test       Passed   1ms
 60 - BetaCircuit_multiplex_Test                Passed   0ms
 61 - BetaCircuit_negate_Test                   Passed   0ms
 62 - BetaCircuit_bitInvert_Test                Passed   0ms
 63 - BetaCircuit_removeSign_Test               Passed   0ms
 64 - BetaCircuit_addSign_Test                  Passed   0ms
 65 - BetaCircuit_json_Tests                    Skipped - USE_JSON not defined.   0ms
 66 - BetaCircuit_bin_Tests                     Passed   3ms
 67 - BetaCircuit_xor_and_lvl_test              Passed   0ms
 68 - BetaCircuit_aes_test                      Passed   3ms
 69 - BetaCircuit_int_Sh3Piecewise_Test         Passed   1ms
 70 - garble_Test                             d30f8ef52bbfbb59f06f1de916187147
  Passed   0ms
071 - Task_schedule_test                        Passed   0ms
072 - Sh3_Runtime_schedule_test                 Passed   0ms
073 - Sh3_Runtime_repeatInput_test              Passed   0ms
074 - Sh3_trim_test                             Passed   3ms
075 - Sh3_Encryptor_IO_test                     Passed   10ms
076 - Sh3_Encryptor_asyncIO_test                Passed   2ms
077 - Sh3_Evaluator_mul_test                    Passed   7ms
078 - Sh3_Evaluator_asyncMul_test               Passed   20ms
079 - Sh3_Evaluator_truncationPai_test          Passed   2ms
080 - Sh3_Evaluator_asyncMul_fixed_test         Passed   1ms
081 - Sh3_Evaluator_asyncMul_matrixFixed_test   Passed   13ms
082 - SharedOT_eval_test                        Passed   2ms
083 - sh3_asyncArithBinMul_test 	              Passed   3ms
084 - sh3_asyncPubArithBinMul_test              Passed   1ms
085 - Sh3_f64_basics_test                       Passed   0ms
086 - Sh3_BinaryEngine_and_test                 Passed   123ms
087 - Sh3_BinaryEngine_add_test                 Passed   135ms
088 - Sh3_BinaryEngine_add_msb_test;            Passed   124ms
089 - Sh3_convert_b64Matrix_PackedBin_test      Passed   2ms
090 - Sh3_Piecewise_plain_test                  Passed   0ms
091 - Sh3_Piecewise_test                        Passed   22ms
092 - lowMC_Circuit_test             Passed   30ms
093 - lowMC_FileCircuit_test         Skipped - USE_JSON not defined   0ms
094 - lowMC_BinFileCircuit_test    verify exp 0000101000111011000011010101010100001010100101001001100100110011110000001011110101100111000001011010110101110001100110000101110111100110100101110110101101100001011000101101001001101011011111010011001111010110011101010001000100001100101001100011111100011110
verify act 1110001010010100000100101110101010110110110001110001101001101001011010110111101010111101001100011100001101001111101010010000000111011001000100010110100111110101111011011011111111101001100110011001100111101000101110111101001110101001000110000100010001110111
Failed - /home/simba/aby3/aby3-DB_tests/lowMC.cpp:315   47ms
095 - DB_computeKeys_test            Passed   127ms
096 - Perm3p_overwrite_Test          Passed   9ms
097 - Perm3p_additive_Test           Passed   0ms
098 - Perm3p_subset_Test             Passed   1ms
099 - switch_select_test             Passed   31ms
100 - switch_duplicate_test          Passed   43ms
101 - switch_full_test               Passed   63ms
102 - DB_cuckooHash_test             Passed   6ms
103 - DB_compare_test                Passed   25ms
104 - DB_Intersect_test              Passed   146ms
105 - DB_Intersect_sl_test           Passed   135ms
106 - DB_Intersect_ls_test           Passed   133ms
107 - DB_leftUnion_test              Passed   121ms

#############################################
           Failed (1)
           Passed (95)
            skipped (12)
#############################################

**Comment by ladnir** [comment]
yeah, I noticed that too. Probably not a big issue.
