### ISSUE TITLE
Compile standalone codes

### ISSUE THREAD

**Issue by imtiyazuddin** [ladnir/aby3#26]
How do we compile standalone codes, using which command?? In case I want to make some changes or write my own sample code, what is the best approach and how do I compile and run ?

**Comment by imtiyazuddin** [comment]
I tried to recreate some command from the make files but it didn't work out. I tries something like this : 

g++ -DBOOST_ALL_NO_LIB -DBOOST_SYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -I/home/imtiyazuddin/Ubuntu/aby3-master/frontend -I/home/imtiyazuddin/Ubuntu/aby3-master/aby3/.. -I/home/imtiyazuddin/Ubuntu/aby3-master -isystem /home/imtiyazuddin/Ubuntu/aby3-master/thirdparty/unix/include -Wall  -maes -msse2 -msse4.1 -msse3 -mavx -mavx2 -mpclmul -Wfatal-errors -pthread -Wno-ignored-attributes -Wno-int-in-bool-context  -std=c++14 -Ofast -DNDEBUG   -std=c++14 -pthread -maes -msse2 -msse3 -mssse3 -msse4.1 -mpclmul -E sample.cpp -o sample

**Comment by ladnir** [comment]
The simplest solution is to write your code as part of the aby3 project . You can just add a new top level folder and then include that in the cmake build system. See aby3-db as an example.

Alternatively, if you want to use your own build system, you'll have to figure out what all you need to link. Generally this is to link:

aby3 
aby3/thirdparty/unix/include

And link:

aby3/thirdparty/unix/lib/*.a
aby3/out/build/linux/aby3/*.a

**Comment by imtiyazuddin** [comment]
thanks, will check it out
