### ISSUE TITLE
How to compute the time consumption for OFFLINE phase

### ISSUE THREAD

**Issue by llCurious** [ladnir/aby3#28]
Hey, when running the code i found a issue that the code to handle the **pre-processing operation (OFFLINE phase) seems to be not implemented so far.**
`void preprocess(u64 n, Decimal d)
		{
			TODO("implement this");
		}`

The public code i think can only test the benchmark of online data and I wonder how to measure the online+offline data.

**Comment by llCurious** [comment]
@ladnir hey, ladnir, could you please give me some suggestions on how to handle above problems?

**Comment by ladnir** [comment]
There's an published optimization that removed the need for the offline phase. I can share the paper if you want to cite it

**Comment by llCurious** [comment]
Oh, that would be of great help, thanks. 

BTW, in my understanding, the offline phase is mainly used for generating the truncatino pair. i.e., r and r/2^d. So, does the optimization remove the need of this operation?

**Comment by ladnir** [comment]
Correct. It works with basically no overhead.

**Comment by llCurious** [comment]
hey, just to check whether you could share me the optimized paper you mentioned above.

**Comment by ladnir** [comment]
Email?

**Comment by llCurious** [comment]
oh sry, this is my email whq1997430@gmail DOT com. Thanks in advance~

**Comment by 1walktheline** [comment]
I'm longing for the optimized paper as well, could you please share it with me if possible? And this is my email Ivy.zxn@gmail.com. Thanks a lot!

**Comment by ladnir** [comment]
Tried to email it but got rejected due to a nonexistent email address.

**Comment by 1walktheline** [comment]
So sorry! If QQ mail available?1332111539@qq.com

**Comment by 1walktheline** [comment]
I'm so sorry! It should be Ivy.zxn6@gmail.com. Thanks!
