### ISSUE TITLE
problem arising when I build and the corresponding solution

### ISSUE THREAD

**Issue by Murlocccc** [ladnir/aby3#29]
## Behavior 1

When "python3 build.py --setup", it reports an error to me that the commond "ARCHIVE_EXTRACT" can not be recognized by cmake. The version of my cmake is v3.16
## Possible Solution 1

"ARCHIVE_EXTRACT" is a commond of cmake v3.18, so the version of cmake should be v3.18 instead of the 3.15 in CMakeLists.txt

## Behavior 2

When "python3 build.py", it reports an error to me that "libOTe/cryptoTools needs to have ENABLE_CIRCUITS defined".
## Possible Solution 2

the code " -- -DENABLE_CIRCUITS=ON " in the 51th row of getLibOTe.py should be changed to " -DENABLE_CIRCUITS=ON "

**Comment by ladnir** [comment]
the 3.18 thing seems right but removing `--` is only required for a newer version of libOTe. 

The current commit `2363505431f744539027a873c2536b9ae3630ff7` does require the `--`. See [here](https://github.com/osu-crypto/libOTe/blob/2363505431f744539027a873c2536b9ae3630ff7/build.py#L34) and [here](https://github.com/ladnir/cryptoTools/blob/139a4b0b53d2f2ed0bee53f8e9e6775d141ddb50/build.py#L118).

Are you using a newer version? We could upgrade if needed.

**Comment by Murlocccc** [comment]
I'm not sure which version I need. What I did is just following the README to build aby3. There is such a sentence in thirdparty/getLibOTe.py:
```
if os.path.isdir("libOTe") == False:
    os.system("git clone --recursive https://github.com/osu-crypto/libOTe.git")
```
It looks like it will download the lastest version of libOTe

**Comment by ladnir** [comment]
https://github.com/ladnir/aby3/blob/master/thirdparty/getLibOTe.py#L14

Im just a bit confused why you are getting that error. The CI is passing https://github.com/ladnir/aby3/actions/runs/1427169242 and I just built it locally in windows and linux (WSL).

**Comment by Murlocccc** [comment]
Oh, it was my fault. The commit I used was still 5584d1a48f46f313c4d3d96be7807ce06a4c1102.  I will try again.

**Comment by ladnir** [comment]
👍
