### ISSUE TITLE
python3 build.py error

### ISSUE THREAD

**Issue by shenpeilin** [ladnir/aby3#30]
when I run python3 build.py, I have the error

CMake Error at out/build/linux/cryptoTools/cmake_install.cmake:69 (file):
  file INSTALL cannot find
  "/home/shenpeilin/aby3/thirdparty/libOTe/out/build/linux/cryptoTools/cryptoTools/libcryptoTools.a":
  No such file or directory.
Call Stack (most recent call first):
  out/build/linux/cmake_install.cmake:47 (include)

I have try to install all of depend packages like boost cmake etc

**Comment by ladnir** [comment]
Can you provide the full output? I just retested on windows and linux (WSL) and it worked.

**Comment by shenpeilin** [comment]
the full is so long,like this:

=========== getLibOTe.py ================
python3 build.py  --par=64 --install=/home/sankuai/aby3/thirdparty/unix  --setup --boost 
python3 build.py  --par=64 --install=/home/sankuai/aby3/thirdparty/unix  -- -DENABLE_CIRCUITS=ON -DCMAKE_PREFIX_PATH=/home/sankuai/aby3/thirdparty/unix
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv




=========== getBoost.py ================
bash bootstrap.sh
 ./b2  -j64 --with-system --with-thread --with-filesystem --with-atomic --with-regex install  --prefix=/home/sankuai/aby3/thirdparty/unix
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv


Building B2 engine..

###
###
### Using 'gcc' toolset.
###
###

> g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


###
###

> g++ -x c++ -std=c++11 -O2 -s -DNDEBUG builtins.cpp class.cpp command.cpp compile.cpp constants.cpp cwd.cpp debug.cpp debugger.cpp execcmd.cpp filesys.cpp frames.cpp function.cpp glob.cpp hash.cpp hcache.cpp hdrmacro.cpp headers.cpp jam.cpp jamgram.cpp lists.cpp make.cpp make1.cpp md5.cpp mem.cpp modules.cpp native.cpp object.cpp option.cpp output.cpp parse.cpp pathsys.cpp regexp.cpp rules.cpp scan.cpp search.cpp jam_strings.cpp startup.cpp subst.cpp sysinfo.cpp timestamp.cpp variable.cpp w32_getreg.cpp modules/order.cpp modules/path.cpp modules/property-set.cpp modules/regex.cpp modules/sequence.cpp modules/set.cpp execunix.cpp fileunix.cpp pathunix.cpp -o b2
> cp b2 bjam
tools/build/src/engine/b2
Detecting Python version... 3.8
Detecting Python root... /opt/anaconda
Unicode/ICU support for Boost.Regex?... not found.
Backing up existing B2 configuration in project-config.jam.3
Generating B2 configuration in project-config.jam for gcc...

Bootstrapping is done. To build, run:

    ./b2
    
To generate header files, run:

    ./b2 headers

To adjust configuration, edit 'project-config.jam'.
Further information:

   - Command line help:
     ./b2 --help
     
   - Getting started guide: 
     http://www.boost.org/more/getting_started/unix-variants.html
     
   - B2 documentation:
     http://www.boost.org/build/

Performing configuration checks

    - default address-model    : 64-bit (cached)
    - default architecture     : x86 (cached)
    - compiler supports SSE2   : yes (cached)
    - compiler supports SSE4.1 : yes (cached)
    - has stat::st_mtim        : yes (cached)
    - has stat::st_mtimensec   : no  (cached)
    - has stat::st_mtimespec   : no  (cached)
    - has stat::st_birthtim    : no  (cached)
    - has stat::st_birthtimensec : no  (cached)
    - has stat::st_birthtimespec : no  (cached)
    - has statx                : no  (cached)
    - has statx syscall        : no  (cached)
    - has_icu builds           : no  (cached)
    - lockfree boost::atomic_flag : yes (cached)

Component configuration:

    - atomic                   : building
    - chrono                   : not building
    - container                : not building
    - context                  : not building
    - contract                 : not building
    - coroutine                : not building
    - date_time                : not building
    - exception                : not building
    - fiber                    : not building
    - filesystem               : building
    - graph                    : not building
    - graph_parallel           : not building
    - headers                  : not building
    - iostreams                : not building
    - json                     : not building
    - locale                   : not building
    - log                      : not building
    - math                     : not building
    - mpi                      : not building
    - nowide                   : not building
    - program_options          : not building
    - python                   : not building
    - random                   : not building
    - regex                    : building
    - serialization            : not building
    - stacktrace               : not building
    - system                   : building
    - test                     : not building
    - thread                   : building
    - timer                    : not building
    - type_erasure             : not building
    - wave                     : not building

...patience...
...patience...
...found 33496 targets...


====== build.py (libOTe) ========
mkdir -p out/build/linux
cmake -S . -B out/build/linux  -DENABLE_CIRCUITS=ON -DCMAKE_PREFIX_PATH=/home/sankuai/aby3/thirdparty/unix -DCMAKE_BUILD_TYPE=Release
cmake --build out/build/linux   --parallel 64 
cmake --install out/build/linux   --prefix /home/sankuai/aby3/thirdparty/unix 
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv


-- cryptoTools options
=======================================================
-- Option: CMAKE_BUILD_TYPE = Release
        Release
        Debug
        RelWithDebInfo
-- Option: ENABLE_RELIC      = OFF
-- Option: ENABLE_SODIUM     = OFF
-- Option: ENABLE_CIRCUITS   = ON
-- Option: ENABLE_NET_LOG    = OFF
-- Option: ENABLE_WOLFSSL    = OFF
-- Option: ENABLE_SSE        = ON
-- Option: ENABLE_BOOST      = ON


-- Boost_LIB: Boost::system;Boost::thread
-- Boost_INC: /usr/local/boost/include


-- General Options
=======================================================
-- Option: ENABLE_ALL_OT         = ON/OFF
-- Base OT protocols
=======================================================
-- Option: ENABLE_SIMPLESTOT     = OFF
-- Option: ENABLE_SIMPLESTOT_ASM = OFF
-- Option: ENABLE_MRR            = OFF
-- Option: ENABLE_MRR_TWIST      = OFF
-- Option: ENABLE_MR             = OFF
-- Option: ENABLE_MR_KYBER       = OFF
-- Option: ENABLE_NP             = OFF


-- 1-out-of-2 OT Extension protocols
=======================================================
-- Option: ENABLE_KOS            = OFF
-- Option: ENABLE_IKNP           = OFF
-- Option: ENABLE_SILENTOT       = OFF


-- 1-out-of-2 Delta-OT Extension protocols
=======================================================
-- Option: ENABLE_DELTA_KOS      = OFF


-- 1-out-of-N OT Extension protocols
=======================================================
-- Option: ENABLE_OOS            = OFF
-- Option: ENABLE_KKRT           = OFF
-- Option: ENABLE_RR             = OFF


CMake Warning at cmake/buildOptions.cmake:125 (message):
  NO Base OT enabled.
Call Stack (most recent call first):
  CMakeLists.txt:72 (include)


-- Configuring done
-- Generating done
-- Build files have been written to: /home/sankuai/aby3/thirdparty/libOTe/out/build/linux
Consolidate compiler generated dependencies of target cryptoTools
[  2%] Building CXX object cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Circuit/BetaCircuit.cpp.o
[  2%] Building CXX object cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Circuit/BetaLibrary.cpp.o
[  3%] Building CXX object cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Common/BitVector.cpp.o
[  4%] Building CXX object cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Common/CLP.cpp.o
[  6%] Building CXX object cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Common/Defines.cpp.o
[  6%] Building CXX object cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Common/CuckooIndex.cpp.o
[  9%] Building CXX object cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Common/TestCollection.cpp.o
[  9%] Building CXX object cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Common/Log.cpp.o
[  9%] Building CXX object cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Common/Timer.cpp.o
[ 10%] Building CXX object cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Common/block.cpp.o
[ 13%] Building CXX object cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Crypto/AES.cpp.o
[ 13%] Building CXX object cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Crypto/Curve.cpp.o
[ 13%] Building CXX object cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Crypto/Blake2.cpp.o
[ 14%] Building CXX object cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Crypto/PRNG.cpp.o
[ 15%] Building CXX object cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Crypto/RCurve.cpp.o
[ 16%] Building CXX object cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Crypto/Rijndael256.cpp.o
[ 18%] Building CXX object cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Network/Channel.cpp.o
[ 18%] Building CXX object cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Crypto/SodiumCurve.cpp.o
[ 20%] Building CXX object cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Network/IoBuffer.cpp.o
[ 21%] Building CXX object cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Network/IOService.cpp.o
c++: error: unrecognized command line option ‘-std=c++17’
c++: error: unrecognized command line option ‘-std=c++14’
[ 22%] Building CXX object cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Network/Session.cpp.o
[ 23%] Building CXX object cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Network/SocketAdapter.cpp.o
c++: error: unrecognized command line option ‘-std=c++17’
c++: error: unrecognized command line option ‘-std=c++14’
c++: error: unrecognized command line option ‘-std=c++17’
c++: error: unrecognized command line option ‘-std=c++14’
[ 24%] Building CXX object cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Network/TLS.cpp.o
gmake[2]: *** [cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Circuit/BetaLibrary.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
c++: error: unrecognized command line option ‘-std=c++17’
c++: error: unrecognized command line option ‘-std=c++14’
gmake[2]: *** [cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Circuit/BetaCircuit.cpp.o] Error 1
gmake[2]: *** [cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Common/BitVector.cpp.o] Error 1
c++: error: unrecognized command line option ‘-std=c++17’
c++: error: unrecognized command line option ‘-std=c++14’
c++: error: unrecognized command line option ‘-std=c++17’
c++: error: unrecognized command line option ‘-std=c++14’
gmake[2]: *** [cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Common/CLP.cpp.o] Error 1
c++: error: unrecognized command line option ‘-std=c++17’
c++: error: unrecognized command line option ‘-std=c++14’
gmake[2]: *** [cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Common/Defines.cpp.o] Error 1
c++: error: unrecognized command line option ‘-std=c++17’
c++: error: unrecognized command line option ‘-std=c++14’
gmake[2]: *** [cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Common/CuckooIndex.cpp.o] Error 1
c++: error: unrecognized command line option ‘-std=c++17’
c++: error: unrecognized command line option ‘-std=c++14’
gmake[2]: *** [cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Common/Timer.cpp.o] Error 1
c++: error: unrecognized command line option ‘-std=c++17’
c++: error: unrecognized command line option ‘-std=c++14’
gmake[2]: *** [cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Common/Log.cpp.o] Error 1
gmake[2]: *** [cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Common/block.cpp.o] Error 1
c++: error: unrecognized command line option ‘-std=c++17’
c++: error: unrecognized command line option ‘-std=c++14’
c++: error: unrecognized command line option ‘-std=c++17’
gmake[2]: c++: error: unrecognized command line option ‘-std=c++14’
*** [cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Crypto/Blake2.cpp.o] Error 1
c++: error: unrecognized command line option ‘-std=c++17’
c++: error: unrecognized command line option ‘-std=c++14’
gmake[2]: *** [cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Crypto/AES.cpp.o] Error 1
gmake[2]: *** [cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Crypto/Curve.cpp.o] Error 1
c++: error: unrecognized command line option ‘-std=c++17’
c++: error: unrecognized command line option ‘-std=c++14’
gmake[2]: *** [cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Crypto/PRNG.cpp.o] Error 1
c++: error: unrecognized command line option ��-std=c++17’
c++: error: unrecognized command line option ‘-std=c++14’
c++: error: unrecognized command line option ‘-std=c++17’
c++: error: unrecognized command line option ‘-std=c++14’
c++: error: unrecognized command line option ‘-std=c++17’
c++: error: unrecognized command line option ‘-std=c++14’
gmake[2]: *** [cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Crypto/RCurve.cpp.o] Error 1
gmake[2]: *** [cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Crypto/Rijndael256.cpp.o] Error 1
gmake[2]: *** [cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Common/TestCollection.cpp.o] Error 1
c++: error: unrecognized command line option ‘-std=c++17’
c++: error: unrecognized command line option ‘-std=c++14’
gmake[2]: *** [cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Network/Channel.cpp.o] Error 1
gmake[2]: *** [cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Network/IoBuffer.cpp.o] Error 1
c++: error: unrecognized command line option ‘-std=c++17’
c++: error: unrecognized command line option ‘-std=c++14’
c++: error: unrecognized command line option ‘-std=c++17’
c++: error: unrecognized command line option ‘-std=c++14’
c++: error: unrecognized command line option ‘-std=c++17’
c++: error: unrecognized command line option ‘-std=c++14’
gmake[2]: *** [cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Network/IOService.cpp.o] Error 1
gmake[2]: *** [cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Network/Session.cpp.o] Error 1
c++: error: unrecognized command line option ‘-std=c++17’
c++: error: unrecognized command line option ‘-std=c++14’
gmake[2]: *** [cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Network/SocketAdapter.cpp.o] Error 1
c++: error: unrecognized command line option ‘-std=c++17’
c++: error: unrecognized command line option ‘-std=c++14’
gmake[2]: *** [cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Crypto/SodiumCurve.cpp.o] Error 1
gmake[2]: *** [cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Network/TLS.cpp.o] Error 1
gmake[1]: *** [cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/all] Error 2
gmake: *** [all] Error 2
-- Install configuration: "Release"
-- Up-to-date: /home/sankuai/aby3/thirdparty/unix/lib64/cmake/cryptoTools/cryptoToolsConfig.cmake
-- Up-to-date: /home/sankuai/aby3/thirdparty/unix/lib64/cmake/cryptoTools/cryptoToolsConfigVersion.cmake
-- Up-to-date: /home/sankuai/aby3/thirdparty/unix/lib64/cmake/cryptoTools/cryptoToolsDepHelper.cmake
CMake Error at out/build/linux/cryptoTools/cmake_install.cmake:69 (file):
  file INSTALL cannot find
  "/home/sankuai/aby3/thirdparty/libOTe/out/build/linux/cryptoTools/cryptoTools/libcryptoTools.a":
  No such file or directory.
Call Stack (most recent call first):
  out/build/linux/cmake_install.cmake:47 (include)


HEAD is now at 3a0746b... Fix reference types in the return type * Closes #35

=========== getFunction2.py =============
mkdir -p /home/sankuai/aby3/thirdparty/unix/include/function2/
cp  -rf ./include/function2 /home/sankuai/aby3/thirdparty/unix/include
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv


=========== getEigen.py =============
mkdir -p /home/sankuai/aby3/thirdparty/unix/include/Eigen/
cp  -rf ./Eigen /home/sankuai/aby3/thirdparty/unix/include
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv


=========== getJson.py =============
mkdir -p /home/sankuai/aby3/thirdparty/unix/include/nlohmann/
cp -rf ./include/nlohmann /home/sankuai/aby3/thirdparty/unix/include
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

**Comment by ladnir** [comment]
Looks like your compiler is out of date

c++: error: unrecognized command line option ‘-std=c++17’
c++: error: unrecognized command line option ‘-std=c++14’

**Comment by 1walktheline** [comment]
This can be solved by using "sudo".
