### ISSUE TITLE
Does intersect implement in aby3 support bit count of key larger than 80?

### ISSUE THREAD

**Issue by Keepmoving-ZXY** [ladnir/aby3#32]
Hello, I want to use aby3's intersect implement as a PSI implement, and I find that bit count of key is fixed to 80 but 256 in our project, so can aby3 support intersect with bit count of key larger than 80? And the source code of intersect is too hard too understand, can you provide me a more detailed documents such as a paper ?

**Comment by Keepmoving-ZXY** [comment]
I have found the paper in `https://github.com/ladnir/aby3/blob/master/tex/ccs20-main.pdf`.

**Comment by ladnir** [comment]
how to do it is described in the paper. I didn't implement it. 

If you are doing PSI with plaintext inputs, you can first pick a hashing key `k` and then compute 80-bit hashes as `x' = H(k, x)`. This gives 80-2*log(n) bits of statistical security, eg 1 in a trillion Pr of error for sets of a million items. 

If the inputs aren't plaintext, you can do what the paper says. But that requires changing the code.

**Comment by Keepmoving-ZXY** [comment]
Thanks for your idea,  I will have a try.
