### ISSUE TITLE
Questions about cmake

### ISSUE THREAD

**Issue by star-123456** [ladnir/aby3#33]
Hello, I'm executing
python3 build. py --setup
The following error is reported during this command:
![ee585da3c2182570f7a765e89bd37c2](https://user-images.githubusercontent.com/67616517/149257554-1b5c4cc3-a185-41ad-b166-11a7471c7652.png)
While executing
python3 build. py
The following errors are reported:
![3bd3a4180598d1350a8dd808540ba19](https://user-images.githubusercontent.com/67616517/149257763-69de421c-bdf6-4891-bfa2-2be27b9dd82d.png)
Why is this problem? Please help me!

**Comment by ladnir** [comment]
"cmake not found" i think that tells you everything you need to know.
