### ISSUE TITLE
test 23 sometimes failed on Centos7

### ISSUE THREAD

**Issue by MDGBDGMG** [ladnir/aby3#34]
bin/frontend -u
  0 - BtNetwork_SBO_ptr_test                    Passed   0ms
  1 - BtNetwork_Connect1_Test                   Passed   0ms
  2 - BtNetwork_RapidConnect_Test               Passed   26ms
  3 - BtNetwork_shutdown_test                   Passed   1ms
  4 - BtNetwork_SocketInterface_Test            Passed   5ms
  5 - BtNetwork_OneMegabyteSend_Test            Passed   3ms
  6 - BtNetwork_ConnectMany_Test                Passed   6ms
  7 - BtNetwork_CrossConnect_Test               Passed   0ms
  8 - BtNetwork_ManySessions_Test               Passed   6ms
  9 - BtNetwork_bitVector_Test                  Passed   0ms
 10 - BtNetwork_AsyncConnect_Test               Passed   1ms
 11 - BtNetwork_std_Containers_Test             Passed   0ms
 12 - BtNetwork_recvErrorHandler_Test           Passed   0ms
 13 - BtNetwork_closeOnError_Test               Passed   0ms
 14 - BtNetwork_AnonymousMode_Test              Passed   0ms
 15 - BtNetwork_CancelChannel_Test              Passed   89ms
 16 - BtNetwork_useAfterCancel_test             Passed   1ms
 17 - BtNetwork_fastCancel                      Passed   23ms
 18 - BtNetwork_ServerMode_Test                 Passed   19ms
 19 - BtNetwork_clientClose_Test                Passed   31ms
 20 - BtNetwork_BadConnect_Test                 Passed   0ms
 21 - BtNetwork_oneWorker_Test                  Passed   0ms
 22 - BtNetwork_queue_Test                      Passed   2ms
 23 - BtNetwork_socketAdapter_test            Segmentation fault

**Comment by ladnir** [comment]
Not sure but given it's on the adapter test probably not an issue. Likely a bug in the dummy socket. You can run the rest of the test with -u 24..100 or whatever the number of test are.

**Comment by MDGBDGMG** [comment]
I tested one by one, and the test results are as follows:

The 70th test case gives strange results

The 94th test case failed to execute

Some test cases are skipped directly, I don't know why
--------------------------------------------------------------------------------------------

 1 - BtNetwork_Connect1_Test                   Passed   0ms

=============================================
            All Passed (1)
=============================================
  2 - BtNetwork_RapidConnect_Test               Passed   26ms

=============================================
            All Passed (1)
=============================================
  3 - BtNetwork_shutdown_test                   Passed   1ms

=============================================
            All Passed (1)
=============================================
  4 - BtNetwork_SocketInterface_Test            Passed   4ms

=============================================
            All Passed (1)
=============================================
  5 - BtNetwork_OneMegabyteSend_Test            Passed   4ms

=============================================
            All Passed (1)
=============================================
  6 - BtNetwork_ConnectMany_Test                Passed   8ms

=============================================
            All Passed (1)
=============================================
  7 - BtNetwork_CrossConnect_Test               Passed   1ms

=============================================
            All Passed (1)
=============================================
  8 - BtNetwork_ManySessions_Test               Passed   6ms

=============================================
            All Passed (1)
=============================================
  9 - BtNetwork_bitVector_Test                  Passed   0ms

=============================================
            All Passed (1)
=============================================
 10 - BtNetwork_AsyncConnect_Test               Passed   1ms

=============================================
            All Passed (1)
=============================================
 11 - BtNetwork_std_Containers_Test             Passed   0ms

=============================================
            All Passed (1)
=============================================
 12 - BtNetwork_recvErrorHandler_Test           Passed   1ms

=============================================
            All Passed (1)
=============================================
 13 - BtNetwork_closeOnError_Test               Passed   1ms

=============================================
            All Passed (1)
=============================================
 14 - BtNetwork_AnonymousMode_Test              Passed   1ms

=============================================
            All Passed (1)
=============================================
 15 - BtNetwork_CancelChannel_Test              Passed   89ms

=============================================
            All Passed (1)
=============================================
 16 - BtNetwork_useAfterCancel_test             Passed   1ms

=============================================
            All Passed (1)
=============================================
 17 - BtNetwork_fastCancel                      Passed   22ms

=============================================
            All Passed (1)
=============================================
 18 - BtNetwork_ServerMode_Test                 Passed   17ms

=============================================
            All Passed (1)
=============================================
 19 - BtNetwork_clientClose_Test                Passed   31ms

=============================================
            All Passed (1)
=============================================
 20 - BtNetwork_BadConnect_Test                 Passed   1ms

=============================================
            All Passed (1)
=============================================
 21 - BtNetwork_oneWorker_Test                  Passed   0ms

=============================================
            All Passed (1)
=============================================
 22 - BtNetwork_queue_Test                      Passed   2ms

=============================================
            All Passed (1)
=============================================
 23 - BtNetwork_socketAdapter_test              Passed   0ms

=============================================
            All Passed (1)
=============================================
 24 - BtNetwork_BasicSocket_test                Passed   1ms

=============================================
            All Passed (1)
=============================================
 25 - wolfSSL_echoServer_test                   Skipped - ENABLE_WOLFSSL not defined   0ms

=============================================
            All Passed (0)
            skipped (1)
=============================================
 26 - wolfSSL_mutualAuth_test                   Skipped - ENABLE_WOLFSSL not defined   0ms

=============================================
            All Passed (0)
            skipped (1)
=============================================
 27 - wolfSSL_channel_test                      Skipped - ENABLE_WOLFSSL not defined   0ms

=============================================
            All Passed (0)
            skipped (1)
=============================================
 28 - wolfSSL_CancelChannel_Test                Skipped - ENABLE_WOLFSSL not defined   0ms

=============================================
            All Passed (0)
            skipped (1)
=============================================
 29 - block_operation_test                      Passed   0ms

=============================================
            All Passed (1)
=============================================
 30 - AES                                       Passed   0ms

=============================================
            All Passed (1)
=============================================
 31 - Rijndael256                               Passed   0ms

=============================================
            All Passed (1)
=============================================
 32 - BitVector_Indexing_Test                   Passed   0ms

=============================================
            All Passed (1)
=============================================
 33 - BitVector_Parity                          Passed   1ms

=============================================
            All Passed (1)
=============================================
 34 - BitVector_Append_Test                     Passed   0ms

=============================================
            All Passed (1)
=============================================
 35 - BitVector_Copy_Test                       Passed   0ms

=============================================
            All Passed (1)
=============================================
 36 - BitVector_Resize_Test                     Passed   0ms

=============================================
            All Passed (1)
=============================================
 37 - CuckooIndex_many_Test                     Passed   21ms

=============================================
            All Passed (1)
=============================================
 38 - CuckooIndex_paramSweep_Test               Passed   65ms

=============================================
            All Passed (1)
=============================================
 39 - CuckooIndex_parallel_Test                 Passed   0ms

=============================================
            All Passed (1)
=============================================
 40 - Ecc2mNumber_Test                          Skipped - ENABLE_MIRACL not defined.   0ms

=============================================
            All Passed (0)
            skipped (1)
=============================================
 41 - Ecc2mPoint_Test                           Skipped - ENABLE_MIRACL not defined.   0ms

=============================================
            All Passed (0)
            skipped (1)
=============================================
 42 - EccpNumber_Test                           Skipped - ENABLE_MIRACL not defined.   0ms

=============================================
            All Passed (0)
            skipped (1)
=============================================
 43 - EccpPoint_Test                            Skipped - ENABLE_MIRACL not defined.   0ms

=============================================
            All Passed (0)
            skipped (1)
=============================================
 44 - REccpNumber_Test                          Skipped - ENABLE_RELIC not defined.   0ms

=============================================
            All Passed (0)
            skipped (1)
=============================================
 45 - REccpPoint_Test                           Skipped - ENABLE_RELIC not defined.   0ms

=============================================
            All Passed (0)
            skipped (1)
=============================================
 46 - BetaCircuit_SequentialOp_Test             Passed   0ms

=============================================
            All Passed (1)
=============================================
 47 - BetaCircuit_int_Adder_Test                Passed   0ms

=============================================
            All Passed (1)
=============================================
 48 - BetaCircuit_int_Adder_const_Test          Passed   4ms

=============================================
            All Passed (1)
=============================================
 49 - BetaCircuit_int_Subtractor_Test           Passed   12ms

=============================================
            All Passed (1)
=============================================
 50 - BetaCircuit_int_Subtractor_const_Test     Passed   5ms

=============================================
            All Passed (1)
=============================================
 51 - BetaCircuit_uint_Adder_Test               Passed   5ms

=============================================
            All Passed (1)
=============================================
 52 - BetaCircuit_uint_Subtractor_Test          Passed   5ms

=============================================
            All Passed (1)
=============================================
 53 - BetaCircuit_int_Multiply_Test             Passed   1ms

=============================================
            All Passed (1)
=============================================
 54 - BetaCircuit_uint_Multiply_Test            Passed   0ms

=============================================
            All Passed (1)
=============================================
 55 - BetaCircuit_int_Divide_Test               Passed   5ms

=============================================
            All Passed (1)
=============================================
 56 - BetaCircuit_int_LessThan_Test             Passed   0ms

=============================================
            All Passed (1)
=============================================
 57 - BetaCircuit_int_GreaterThanEq_Test        Passed   0ms

=============================================
            All Passed (1)
=============================================
 58 - BetaCircuit_uint_LessThan_Test            Passed   0ms

=============================================
            All Passed (1)
=============================================
 59 - BetaCircuit_uint_GreaterThanEq_Test       Passed   0ms

=============================================
            All Passed (1)
=============================================
 60 - BetaCircuit_multiplex_Test                Passed   0ms

=============================================
            All Passed (1)
=============================================
 61 - BetaCircuit_negate_Test                   Passed   0ms

=============================================
            All Passed (1)
=============================================
 62 - BetaCircuit_bitInvert_Test                Passed   0ms

=============================================
            All Passed (1)
=============================================
 63 - BetaCircuit_removeSign_Test               Passed   0ms

=============================================
            All Passed (1)
=============================================
 64 - BetaCircuit_addSign_Test                  Passed   0ms

=============================================
            All Passed (1)
=============================================
 65 - BetaCircuit_json_Tests                    Skipped - USE_JSON not defined.   0ms

=============================================
            All Passed (0)
            skipped (1)
=============================================
 66 - BetaCircuit_bin_Tests                     Passed   3ms

=============================================
            All Passed (1)
=============================================
 67 - BetaCircuit_xor_and_lvl_test              Passed   0ms

=============================================
            All Passed (1)
=============================================
 68 - BetaCircuit_aes_test                      Passed   4ms

=============================================
            All Passed (1)
=============================================
 69 - BetaCircuit_int_Sh3Piecewise_Test         Passed   1ms

=============================================
            All Passed (1)
=============================================
 70 - garble_Test                             d30f8ef52bbfbb59f06f1de916187147
  Passed   0ms

=============================================
            All Passed (1)
=============================================
 71 - Task_schedule_test                        Passed   0ms

=============================================
            All Passed (1)
=============================================
 72 - Sh3_Runtime_schedule_test                 Passed   0ms

=============================================
            All Passed (1)
=============================================
 73 - Sh3_Runtime_repeatInput_test              Passed   0ms

=============================================
            All Passed (1)
=============================================
 74 - Sh3_trim_test                             Passed   4ms

=============================================
            All Passed (1)
=============================================
 75 - Sh3_Encryptor_IO_test                     Passed   3ms

=============================================
            All Passed (1)
=============================================
 76 - Sh3_Encryptor_asyncIO_test                Passed   1ms

=============================================
            All Passed (1)
=============================================
 77 - Sh3_Evaluator_mul_test                    Passed   3ms

=============================================
            All Passed (1)
=============================================
 78 - Sh3_Evaluator_asyncMul_test               Passed   8ms

=============================================
            All Passed (1)
=============================================
 79 - Sh3_Evaluator_truncationPai_test          Passed   2ms

=============================================
            All Passed (1)
=============================================
 80 - Sh3_Evaluator_asyncMul_fixed_test         Passed   1ms

=============================================
            All Passed (1)
=============================================
 81 - Sh3_Evaluator_asyncMul_matrixFixed_test   Passed   5ms

=============================================
            All Passed (1)
=============================================
 82 - SharedOT_eval_test                        Passed   2ms

=============================================
            All Passed (1)
=============================================
 83 - sh3_asyncArithBinMul_test                       Passed   2ms

=============================================
            All Passed (1)
=============================================
 84 - sh3_asyncPubArithBinMul_test              Passed   1ms

=============================================
            All Passed (1)
=============================================
 85 - Sh3_f64_basics_test                       Passed   0ms

=============================================
            All Passed (1)
=============================================
 86 - Sh3_BinaryEngine_and_test                 Passed   77ms

=============================================
            All Passed (1)
=============================================
 87 - Sh3_BinaryEngine_add_test                 Passed   78ms

=============================================
            All Passed (1)
=============================================
 88 - Sh3_BinaryEngine_add_msb_test;            Passed   76ms

=============================================
            All Passed (1)
=============================================
 89 - Sh3_convert_b64Matrix_PackedBin_test      Passed   2ms

=============================================
            All Passed (1)
=============================================
 90 - Sh3_Piecewise_plain_test                  Passed   0ms

=============================================
            All Passed (1)
=============================================
 91 - Sh3_Piecewise_test                        Passed   25ms

=============================================
            All Passed (1)
=============================================
 92 - lowMC_Circuit_test             Passed   29ms

=============================================
            All Passed (1)
=============================================
 93 - lowMC_FileCircuit_test         Skipped - USE_JSON not defined   0ms

=============================================
            All Passed (0)
            skipped (1)
=============================================
 94 - lowMC_BinFileCircuit_test    verify exp 0000101000111011000011010101010100001010100101001001100100110011110000001011110101100111000001
011010110101110001100110000101110111100110100101110110101101100001011000101101001001101011011111010011001111010110011101010001000100001100101001100011111
100011110
verify act 1110001010010100000100101110101010110110110001110001101001101001011010110111101010111101001100011100001101001111101010010000000111011001000100
010110100111110101111011011011111111101001100110011001100111101000101110111101001110101001000110000100010001110111
Failed - /root/aby3/aby3-DB_tests/lowMC.cpp:315   50ms

#############################################
           Failed (1)
           Passed (0)
#############################################
 95 - DB_computeKeys_test            Passed   270ms

=============================================
            All Passed (1)
=============================================
 96 - Perm3p_overwrite_Test          Passed   12ms

=============================================
            All Passed (1)
=============================================
 97 - Perm3p_additive_Test           Passed   1ms

=============================================
            All Passed (1)
=============================================
 98 - Perm3p_subset_Test             Passed   1ms

=============================================
            All Passed (1)
=============================================
 99 - switch_select_test             Passed   14ms

=============================================
            All Passed (1)
=============================================
100 - switch_duplicate_test          Passed   18ms

=============================================
            All Passed (1)
=============================================
101 - switch_full_test               Passed   34ms

=============================================
            All Passed (1)
=============================================
102 - DB_cuckooHash_test             Passed   7ms

=============================================
            All Passed (1)
=============================================
103 - DB_compare_test                Passed   21ms

=============================================
            All Passed (1)
=============================================
104 - DB_Intersect_test              Passed   257ms

=============================================
            All Passed (1)
=============================================
105 - DB_Intersect_sl_test           Passed   244ms

=============================================
            All Passed (1)
=============================================
106 - DB_Intersect_ls_test           Passed   250ms

=============================================
            All Passed (1)
=============================================
107 - DB_leftUnion_test              Passed   227ms

=============================================
            All Passed (1)
=============================================

**Comment by MDGBDGMG** [comment]
I tested one by one, and the test results are as follows:

The 70th test case gives strange results

The 94th test case failed to execute

Some test cases are skipped directly, I don't know why

---------------------------------------------------------------
1 - BtNetwork_Connect1_Test                   Passed   0ms


            All Passed (1)

  2 - BtNetwork_RapidConnect_Test               Passed   26ms


            All Passed (1)

  3 - BtNetwork_shutdown_test                   Passed   1ms


            All Passed (1)

  4 - BtNetwork_SocketInterface_Test            Passed   4ms


            All Passed (1)

  5 - BtNetwork_OneMegabyteSend_Test            Passed   4ms


            All Passed (1)

  6 - BtNetwork_ConnectMany_Test                Passed   8ms


            All Passed (1)

  7 - BtNetwork_CrossConnect_Test               Passed   1ms


            All Passed (1)

  8 - BtNetwork_ManySessions_Test               Passed   6ms


            All Passed (1)

  9 - BtNetwork_bitVector_Test                  Passed   0ms


            All Passed (1)

 10 - BtNetwork_AsyncConnect_Test               Passed   1ms


            All Passed (1)

 11 - BtNetwork_std_Containers_Test             Passed   0ms


            All Passed (1)

 12 - BtNetwork_recvErrorHandler_Test           Passed   1ms


            All Passed (1)

 13 - BtNetwork_closeOnError_Test               Passed   1ms


            All Passed (1)

 14 - BtNetwork_AnonymousMode_Test              Passed   1ms


            All Passed (1)

 15 - BtNetwork_CancelChannel_Test              Passed   89ms


            All Passed (1)

 16 - BtNetwork_useAfterCancel_test             Passed   1ms


            All Passed (1)

 17 - BtNetwork_fastCancel                      Passed   22ms


            All Passed (1)

 18 - BtNetwork_ServerMode_Test                 Passed   17ms


            All Passed (1)

 19 - BtNetwork_clientClose_Test                Passed   31ms


            All Passed (1)

 20 - BtNetwork_BadConnect_Test                 Passed   1ms


            All Passed (1)

 21 - BtNetwork_oneWorker_Test                  Passed   0ms


            All Passed (1)

 22 - BtNetwork_queue_Test                      Passed   2ms


            All Passed (1)

 23 - BtNetwork_socketAdapter_test              Passed   0ms


            All Passed (1)

 24 - BtNetwork_BasicSocket_test                Passed   1ms


            All Passed (1)

 25 - wolfSSL_echoServer_test                   Skipped - ENABLE_WOLFSSL not defined   0ms


            All Passed (0)
            skipped (1)

 26 - wolfSSL_mutualAuth_test                   Skipped - ENABLE_WOLFSSL not defined   0ms


            All Passed (0)
            skipped (1)

 27 - wolfSSL_channel_test                      Skipped - ENABLE_WOLFSSL not defined   0ms


            All Passed (0)
            skipped (1)

 28 - wolfSSL_CancelChannel_Test                Skipped - ENABLE_WOLFSSL not defined   0ms


            All Passed (0)
            skipped (1)

 29 - block_operation_test                      Passed   0ms


            All Passed (1)

 30 - AES                                       Passed   0ms


            All Passed (1)

 31 - Rijndael256                               Passed   0ms


            All Passed (1)

 32 - BitVector_Indexing_Test                   Passed   0ms


            All Passed (1)

 33 - BitVector_Parity                          Passed   1ms


            All Passed (1)

 34 - BitVector_Append_Test                     Passed   0ms


            All Passed (1)

 35 - BitVector_Copy_Test                       Passed   0ms


            All Passed (1)

 36 - BitVector_Resize_Test                     Passed   0ms


            All Passed (1)

 37 - CuckooIndex_many_Test                     Passed   21ms


            All Passed (1)

 38 - CuckooIndex_paramSweep_Test               Passed   65ms


            All Passed (1)

 39 - CuckooIndex_parallel_Test                 Passed   0ms


            All Passed (1)

 40 - Ecc2mNumber_Test                          Skipped - ENABLE_MIRACL not defined.   0ms


            All Passed (0)
            skipped (1)

 41 - Ecc2mPoint_Test                           Skipped - ENABLE_MIRACL not defined.   0ms


            All Passed (0)
            skipped (1)

 42 - EccpNumber_Test                           Skipped - ENABLE_MIRACL not defined.   0ms


            All Passed (0)
            skipped (1)

 43 - EccpPoint_Test                            Skipped - ENABLE_MIRACL not defined.   0ms


            All Passed (0)
            skipped (1)

 44 - REccpNumber_Test                          Skipped - ENABLE_RELIC not defined.   0ms


            All Passed (0)
            skipped (1)

 45 - REccpPoint_Test                           Skipped - ENABLE_RELIC not defined.   0ms


            All Passed (0)
            skipped (1)

 46 - BetaCircuit_SequentialOp_Test             Passed   0ms


            All Passed (1)

 47 - BetaCircuit_int_Adder_Test                Passed   0ms


            All Passed (1)

 48 - BetaCircuit_int_Adder_const_Test          Passed   4ms


            All Passed (1)

 49 - BetaCircuit_int_Subtractor_Test           Passed   12ms


            All Passed (1)

 50 - BetaCircuit_int_Subtractor_const_Test     Passed   5ms


            All Passed (1)

 51 - BetaCircuit_uint_Adder_Test               Passed   5ms


            All Passed (1)

 52 - BetaCircuit_uint_Subtractor_Test          Passed   5ms


            All Passed (1)

 53 - BetaCircuit_int_Multiply_Test             Passed   1ms


            All Passed (1)

 54 - BetaCircuit_uint_Multiply_Test            Passed   0ms


            All Passed (1)

 55 - BetaCircuit_int_Divide_Test               Passed   5ms


            All Passed (1)

 56 - BetaCircuit_int_LessThan_Test             Passed   0ms


            All Passed (1)

 57 - BetaCircuit_int_GreaterThanEq_Test        Passed   0ms


            All Passed (1)

 58 - BetaCircuit_uint_LessThan_Test            Passed   0ms


            All Passed (1)

 59 - BetaCircuit_uint_GreaterThanEq_Test       Passed   0ms


            All Passed (1)

 60 - BetaCircuit_multiplex_Test                Passed   0ms


            All Passed (1)

 61 - BetaCircuit_negate_Test                   Passed   0ms


            All Passed (1)

 62 - BetaCircuit_bitInvert_Test                Passed   0ms


            All Passed (1)

 63 - BetaCircuit_removeSign_Test               Passed   0ms


            All Passed (1)

 64 - BetaCircuit_addSign_Test                  Passed   0ms


            All Passed (1)

 65 - BetaCircuit_json_Tests                    Skipped - USE_JSON not defined.   0ms


            All Passed (0)
            skipped (1)

 66 - BetaCircuit_bin_Tests                     Passed   3ms


            All Passed (1)

 67 - BetaCircuit_xor_and_lvl_test              Passed   0ms


            All Passed (1)

 68 - BetaCircuit_aes_test                      Passed   4ms


            All Passed (1)

 69 - BetaCircuit_int_Sh3Piecewise_Test         Passed   1ms


            All Passed (1)

 70 - garble_Test                             d30f8ef52bbfbb59f06f1de916187147
  Passed   0ms


            All Passed (1)

 71 - Task_schedule_test                        Passed   0ms


            All Passed (1)

 72 - Sh3_Runtime_schedule_test                 Passed   0ms


            All Passed (1)

 73 - Sh3_Runtime_repeatInput_test              Passed   0ms


            All Passed (1)

 74 - Sh3_trim_test                             Passed   4ms


            All Passed (1)

 75 - Sh3_Encryptor_IO_test                     Passed   3ms


            All Passed (1)

 76 - Sh3_Encryptor_asyncIO_test                Passed   1ms


            All Passed (1)

 77 - Sh3_Evaluator_mul_test                    Passed   3ms


            All Passed (1)

 78 - Sh3_Evaluator_asyncMul_test               Passed   8ms


            All Passed (1)

 79 - Sh3_Evaluator_truncationPai_test          Passed   2ms


            All Passed (1)

 80 - Sh3_Evaluator_asyncMul_fixed_test         Passed   1ms


            All Passed (1)

 81 - Sh3_Evaluator_asyncMul_matrixFixed_test   Passed   5ms


            All Passed (1)

 82 - SharedOT_eval_test                        Passed   2ms


            All Passed (1)

 83 - sh3_asyncArithBinMul_test                       Passed   2ms


            All Passed (1)

 84 - sh3_asyncPubArithBinMul_test              Passed   1ms


            All Passed (1)

 85 - Sh3_f64_basics_test                       Passed   0ms


            All Passed (1)

 86 - Sh3_BinaryEngine_and_test                 Passed   77ms


            All Passed (1)

 87 - Sh3_BinaryEngine_add_test                 Passed   78ms


            All Passed (1)

 88 - Sh3_BinaryEngine_add_msb_test;            Passed   76ms


            All Passed (1)

 89 - Sh3_convert_b64Matrix_PackedBin_test      Passed   2ms


            All Passed (1)

 90 - Sh3_Piecewise_plain_test                  Passed   0ms


            All Passed (1)

 91 - Sh3_Piecewise_test                        Passed   25ms


            All Passed (1)

 92 - lowMC_Circuit_test             Passed   29ms


            All Passed (1)

 93 - lowMC_FileCircuit_test         Skipped - USE_JSON not defined   0ms


            All Passed (0)
            skipped (1)

 94 - lowMC_BinFileCircuit_test    verify exp 0000101000111011000011010101010100001010100101001001100100110011110000001011110101100111000001
011010110101110001100110000101110111100110100101110110101101100001011000101101001001101011011111010011001111010110011101010001000100001100101001100011111
100011110
verify act 1110001010010100000100101110101010110110110001110001101001101001011010110111101010111101001100011100001101001111101010010000000111011001000100
010110100111110101111011011011111111101001100110011001100111101000101110111101001110101001000110000100010001110111
Failed - /root/aby3/aby3-DB_tests/lowMC.cpp:315   50ms

#############################################
           Failed (1)
           Passed (0)
#############################################
 95 - DB_computeKeys_test            Passed   270ms


            All Passed (1)

 96 - Perm3p_overwrite_Test          Passed   12ms


            All Passed (1)

 97 - Perm3p_additive_Test           Passed   1ms


            All Passed (1)

 98 - Perm3p_subset_Test             Passed   1ms


            All Passed (1)

 99 - switch_select_test             Passed   14ms


            All Passed (1)

100 - switch_duplicate_test          Passed   18ms


            All Passed (1)

101 - switch_full_test               Passed   34ms


            All Passed (1)

102 - DB_cuckooHash_test             Passed   7ms


            All Passed (1)

103 - DB_compare_test                Passed   21ms


            All Passed (1)

104 - DB_Intersect_test              Passed   257ms


            All Passed (1)

105 - DB_Intersect_sl_test           Passed   244ms


            All Passed (1)

106 - DB_Intersect_ls_test           Passed   250ms


            All Passed (1)

107 - DB_leftUnion_test              Passed   227ms


            All Passed (1)

**Comment by ladnir** [comment]
That's fine, garbling isn't used

**Comment by MDGBDGMG** [comment]
Is the aby3 framework normal? I can use the aby3 framework normally?

**Comment by ladnir** [comment]
Ha, sure. It's normal and largely works. Is it perfect, no.
