### ISSUE TITLE
Can aby3 compare two numbers?

### ISSUE THREAD

**Issue by qwerfdg** [ladnir/aby3#35]
I found these codes about comparison but they were commented out. So, can aby3 compare two numbers and where I can find some examples? 
https://github.com/ladnir/aby3/blob/161af77e32181cad997227340bbe0149ab5cf13f/aby3_tests/Sh3BinaryEvaluatorTests.cpp#L51

**Comment by ladnir** [comment]
Yes, you can use binary secret share and use the equally circuit to get the result. Reopen if you still need help
