### ISSUE TITLE
client socket connect error

### ISSUE THREAD

**Issue by WeiViming** [ladnir/aby3#36]
Hello. When I try to run the test, it return the following problem.
```
> ./bin/frontend -u
  0 - BtNetwork_SBO_ptr_test                    Passed   0ms
  1 - BtNetwork_Connect1_Test                 Permission denied
client socket connect error (hangs).
```
I retry with `sudo`, but the same problem still exists. 

What should I do? Thank you.

**Comment by ladnir** [comment]
Looks like the application was denied permission to bind the port that the unit tests use. I think it's 1212. Not sure if there's a good solution you could edit the unit tests to use some other port.

**Comment by WeiViming** [comment]
Sad to say that it failed, again.
