### ISSUE TITLE
error on -DCMAKE_BUILD_TYPE=Debug

### ISSUE THREAD

**Issue by muou55555** [ladnir/aby3#38]
I try to run "frontend" on debug mode, program generation segment  errors, but it is OK on release mode

**Comment by ladnir** [comment]
It's unclear how I'm supposed to help you from your description. Attached a debugger and see where it segfaults.

**Comment by muou55555** [comment]
> It's unclear how I'm supposed to help you from your description. Attached a debugger and see where it segfaults.

I run "frontend -linear" on debug mode. errors follow:
![image](https://user-images.githubusercontent.com/5515510/184114219-6177a38c-9deb-41ca-a5c1-bd2590be8420.png)
![image](https://user-images.githubusercontent.com/5515510/184114302-8e91bd7b-e982-48a9-99cd-3fb80d2dbedb.png)
![image](https://user-images.githubusercontent.com/5515510/184114339-1018199f-f629-40c5-a723-8650f3d2b892.png)

But, it's sucessful on release mode.

**Comment by muou55555** [comment]
> > It's unclear how I'm supposed to help you from your description. Attached a debugger and see where it segfaults.
> 
> I run "frontend -linear" on debug mode. errors follow: ![image](https://user-images.githubusercontent.com/5515510/184114219-6177a38c-9deb-41ca-a5c1-bd2590be8420.png) ![image](https://user-images.githubusercontent.com/5515510/184114302-8e91bd7b-e982-48a9-99cd-3fb80d2dbedb.png) ![image](https://user-images.githubusercontent.com/5515510/184114339-1018199f-f629-40c5-a723-8650f3d2b892.png)
> 
> But, it's sucessful on release mode.

I think it maybe network related problem。

**Comment by ladnir** [comment]
Yeah, looks networking related. Unclear how I can debug that. Unfortunately maybe the best solution is to try a different computer.

**Comment by muou55555** [comment]
> Yeah, looks networking related. Unclear how I can debug that. Unfortunately maybe the best solution is to try a different computer.

Thanks! I will try it again. ^_^

**Comment by muou55555** [comment]
> 

I have located the problem, but I don't know how to fix it。
error found in remoteIntMatrix or localIntMatrix
`int linear_main_3pc_sh(int N, int Dim, int B, int IT, int testN, int pIdx, bool print, CLP& cmd, Session& chlPrev, Session& chlNext)
`
......
`
Sh3Task Sh3Encryptor::localIntMatrix(Sh3Task dep, const i64Matrix & m, si64Matrix & ret)
`or
`
`
Sh3Task Sh3Encryptor::remoteIntMatrix(Sh3Task dep, si64Matrix & ret)
`
When the matrix size is too large, the error will reappear。When I run with a smaller matrix（10*10） size, I can succeed.
I'm trying to solve it, but difficulty.

**Comment by ladnir** [comment]
Yeah my guess it will be non trivial to fix...
