### ISSUE TITLE
Distributed example needed

### ISSUE THREAD

**Issue by vincehong** [ladnir/aby3#4]
Currently the frontend.exe example is based on a single machine. Is it possible to test in a real 3-machine environment?

**Comment by ladnir** [comment]
Yes, it is possible. The `-p` argument is how you control this. Without it all parties run. To run party `i\in{0,1,2}` pass `-p i`

**Comment by ladnir** [comment]
Well actually things still run just on localhost... You will need to edit the examples.

Here is where networking is setup https://github.com/ladnir/aby3/blob/master/aby3-ML/main-linear.cpp#L201

You will need to set the IP:port correctly. See here for an explanation of networking. https://github.com/ladnir/cryptoTools/blob/master/frontend_cryptoTools/Tutorials/Network.cpp#L44
