### ISSUE TITLE
Question about "LessThen" operator when working with DBs

### ISSUE THREAD

**Issue by niklasUPB** [ladnir/aby3#40]
I have a question about the LessThen operator when working with  SelectBundels. 
I have checked eric.cpp and tried to do sth. similar. Yet I get results that seem incorrect to me and I am unable to see what I am doing wrong. My Code is very similar to eric.cpp.
![code](https://user-images.githubusercontent.com/105489239/186838892-3fb990d7-0085-424b-9611-f859d3ec0ab6.png)

But when I use it with the following inputs :
A=
![a1](https://user-images.githubusercontent.com/105489239/186836279-887b8f25-6fcc-4bba-83bc-8941c26d4e79.PNG)
C=
![c2](https://user-images.githubusercontent.com/105489239/186836291-95628a33-7f6d-4c90-b5a4-742e2a8c64f0.png)

I get the following output.
![out](https://user-images.githubusercontent.com/105489239/186836268-b4c4f419-3e73-4e88-a73c-b392efcb2df7.png)

I would expect to larger column to look very different.
More like
|a1 |         c1  |      larger
|---|---|---|
|-586     |  790       |1|
|240        |672       |1|
|-153       |422       |1|
|184        |328       |1|
|-947       |295       |1|
|610        |895        |1|
|-395       |752       |1|
|383       |41          |0|
|-72        | 30         |1|
|949        | 878       |0|   

The problem also arises with different inputs. I have tried on two different machines and observed identical behavior.
I am uncertain what causes this behavior and would appreciate help very much.

**Comment by ladnir** [comment]
Not sure, I'll try to take a look soon.
