### ISSUE TITLE
Confused about the comparison circuit in ABY3

### ISSUE THREAD

**Issue by Fannxy** [ladnir/aby3#41]
Greetings

Currently, we want to implement greater-than function about two secret fixed-points (sf64) in ABY3, and the interfaces between secret ints and circuits raise some confusion.

In my understanding, the greater-than function should be organized as ``sbMatrix res = msb( si64 a.mShares - si64 b.mShares)`` in ABY3, where ``a`` and ``b`` are  all ``sf64``. The steps including:

1) transfer the sf64 to corresponding si64 a.mShare and b.mShare;
2) use the ``int_int_sub_msb_build_do`` circuit function to compute for the msb.

Here we at first think the ``int`` and ``int`` are corresponding ``si64 a`` and ``si64 b``, while it seems we should put two ``i64`` for the ``int_int_sub_msb_build_do`` circuit. 

Could you please tell us how to implement such function ? we got confused to know which share should the corresponding party pass to the circuit.

Thanks a lot!

**Comment by ladnir** [comment]
The idea is to first compute c=a-b.

Then the msb of c is 1 if b>a.

For semi honest, you can compress the shares of c (3 of them) into two shares c1, c2 such that c1+c2=c. You do this by having one party add their shares together.

You then use the add_msb circuit to to add c1, c2 and get the msb. You could also use sub_msb if you use c1, (-c2) as inputs. 

Regardless, you input these 64 bit values into the  sh3BinaryEvaluator to evaluate the binary circuit on these inputs.

**Comment by Fannxy** [comment]
Thanks for your reply, it is now clear to me.

I tried to implement the above circuit referenced  to [``int_Sh3Piecewise_helper`` function](https://github.com/ladnir/aby3/blob/master/aby3/Circuit/CircuitLibrary.cpp#L9)  and some problem happened during running.

As our function is to compare two ``si`` values, our circuit is implemented as:

```c++
oc::BetaCircuit* CircuitLibrary::gt_build_do(){
    auto key = "gt_circuit";
    auto iter = mCirMap.find(key);
    const auto unit_size = sizeof(i64) * 8;

    if (iter == mCirMap.end())
    {
        auto* cd = new BetaCircuit;
        BetaBundle ba(unit_size);
        BetaBundle bb(unit_size);
        BetaBundle msb(1);
        BetaBundle temps(bb.mWires.size() * 2);

        // temps.mWires.resize(bb.mWires.size() * 2);
        std::cout << "mWires size ba: " << ba.mWires.size() << std::endl; // 64
        std::cout << "mWires size bb: " << bb.mWires.size() << std::endl; // 64
        std::cout << "output size: " << msb.mWires.size() << std::endl; // 1
        std::cout << "tmp size: " << temps.mWires.size() << std::endl; // 128

        cd->addInputBundle(ba);
        cd->addInputBundle(bb);
        cd->addOutputBundle(msb);
        cd->addTempWireBundle(temps);
        cd->addTempWireBundle(msb);

        std::cout << "succeed here" << std::endl;
        int_int_add_msb_build_do(*cd, ba, bb, msb, temps);
        std::cout << " after build do " << std::endl;
        iter = mCirMap.insert(std::make_pair(key, cd)).first;
    }
    return iter->second;
}
```

The output sizes are shown as the comment behind ``std::cout``, which are consistent with the ``int_add_msb`` circuit in my understanding.

During execution, the program behaves as if the size or something is incorrect, some parties may succeed to print ``after build do`` and others may not, and sometimes the ``succeed here`` are not all printed by all the parties. I think the circuit we implemented are similar with your ``int_Sh3Piecewise_helper``, for both logic and bundle sizes.

Is there exist anything wrong with my understanding or the code? 

Thanks a lot !

**Comment by ladnir** [comment]
Not sure. One big I see is that you have

cd->addTempWireBundle(msb)

msb should only be an output, not a temp. You should attach a debugger and see why some parties are throwing or crashing.

**Comment by Fannxy** [comment]
I have succeed for matrix inputs, and the results seem correct. 
Thanks for your help!
