### ISSUE TITLE
Some problematic results of ``int_eq`` circuit.

### ISSUE THREAD

**Issue by Fannxy** [ladnir/aby3#42]
Greetings, we found some problematic outputs when implementing equal test using ``int_eq`` circuit (defined in cryptoTools).

When we implementing the equal test for two si64 matrices, the result are always ``0`` whether for equal or unequal elements.

For example, we define ``si64Matrix isharedA`` and ``isharedB`` as following:

```c++
i64Matrix iplainA(rows, cols);
i64Matrix iplainB(rows, cols);

for(u64 j=0; j<rows; j++){
	for (u64 i = 0; i<cols; i++){
	  iplainA(j, i) = j;
	  iones(j, i) = 1;
	  // iplainB(j, i) = j;
	  if (j%2 == 0) iplainB(j, i) = j + 1;
	  else iplainB(j, i) = j;
	}
} 

// the following code is executed by each party (pIdx)
si64Matrix isharedA(iplainA.rows(), iplainA.cols());
si64Matrix isharedB(iplainB.rows(), iplainB.cols());

if(pIdx == 0){
	enc.localIntMatrix(runtime, iplainA, isharedA).get();
	enc.localIntMatrix(runtime, iplainB, isharedB).get();
}
else{
	enc.remoteIntMatrix(runtime, isharedA).get();
	enc.remoteIntMatrix(runtime, isharedB).get();
}
```
where ``isharedA = [0, 1, 2, 3, 4, 5 ..., nrows]`` and ``isharedB = [1, 1, 3, 3, 5, 5 ... ]``, all the odd indexed elements are equal with ``isharedA``.
Then we implement the equal test for ``isharedA`` and ``isharedB`` as following:

```c++
// defined for each party (pIdx).
Sh3BinaryEvaluator binEng;
CircuitLibrary lib;
sbMatrix circuitInput0;
sbMatrix circuitInput1;
sbMatrix res;

circuitInput0.resize(isharedA.size(), 64);
circuitInput1.resize(isharedB.size(), 64);

// generate the corresponding binary inputs.
memcpy(circuitInput0.mShares[0].data(), isharedA.mShares[0].data(), isharedA.size() * sizeof(i64));
memcpy(circuitInput0.mShares[1].data(), isharedA.mShares[1].data(), isharedA.size() * sizeof(i64));
memcpy(circuitInput1.mShares[0].data(), isharedB.mShares[0].data(), isharedB.size() * sizeof(i64));
memcpy(circuitInput1.mShares[1].data(), isharedB.mShares[1].data(), isharedB.size() * sizeof(i64));

// define the eq test circuit and execute
auto cir = lib.int_eq(sizeof(i64)*8);
binEng.setCir(cir, intA.size(), eval.mShareGen);
binEng.setInput(0, circuitInput0);
binEng.setInput(1, circuitInput1);
binEng.asyncEvaluate(runtime).then([&](Sh3Task self) {
  res.resize(intA.size(), 1);
  binEng.getOutput(0, res);
}).get();
```
we expect the result in res should be ``[0, 1, 0, 1, 0, 1, ...]`` the eq result should be one ``0`` and then one ``1``, but the result are all ``0``.

Is the use of ``int_eq`` circuit right? or there indeed exist some problem...

ps, the result of ``int_neq`` is all ``1``.

Thanks for your help.

**Comment by Fannxy** [comment]
I checked the logic of ABY3 evaluating ``int_eq`` circuit, it computes ``NXor`` for every bit of the inputs and ``And`` them all. I think this logic is suited for binary shares where the ``Xor`` of all the three shares represent the corresponding bit of the arithmetic int input. 
While the conversion of A share to B share function, aka function ``toPackedBin``(in my understanding) just throws an exception... Is there any way to convert the A share to B share in ABY3? 

Thanks for your help!

**Comment by ladnir** [comment]
First get a 2 out of 2 secret share. Then have you put the parties input these. The eq circuit will then work.

**Comment by Fannxy** [comment]
If i want to compute ``a == b`` for two arthimetric shares ``a = a1+a2+a3`` and ``b = b1+b2+b3``, then, how to do the (2, 2) secret shareing conversion? 

Suppose the input of the ``int_eq`` circuit is circuitInput0 and circuitInput1, where each party Pi (i = 1, 2, 3) holds two shares (referenced from the logic of computing msb in piecewise polynomial, letting one party add its shares).

Is the circuit inputs circuitInput0 and circuitInput1 organized as the follows? which i think there exist some problem about privacy...

|| P1 (holds (a1, a2; b1, b2)) | P2 (holds (a2, a3; b2, b3)) | P3 (holds (a3, a1; b3, b1)) |
| :----:| :----:| :----: | :----: |
|CircuitInput0 shares0| a1 + a2 | a3 | 0 |
|CircuitInput0 shares1| 0 | a1 + a2 | a3 |
|CircuitInput1 shares0| b1 + b2 | b3 | 0 |
|CircuitInput1 shares1| 0 | b1 + b2 | b3 |

I don't think there is any way to avoid one party holding all shares of one value (in the above case, P1 knows a = a3 + a1 + a2) if the (2, 2) shares construction way is to let one party add its shares together and reshare to its next party... which breaks the privacy.

Is there any misunderstanding about computing the equal of two secret int? each is represented as the sum of three shares.

Thanks, again!

**Comment by ladnir** [comment]
Sorry, wasn't the most clear.

First subtract the shares [c] =[a] - [b]

Then c'1=c1, c'2=c2+c3

Then compute c'1==c'2 using eq

**Comment by ladnir** [comment]
P1 will hold c'1, p2 will hold c'2. You will have to convert these plaintext arithmetic values into binary shares. This is done using normal binary secret sharing.

You can optimize it a bit by letting two parties learn one of c'1 or c'2. The sharing for that one can then be c'i for those two parties common share and the zero for the other shares. But maybe that's more complicated than it's worth.

The code base should have this pattern somewhere.

**Comment by Fannxy** [comment]
Thanks for your response! i will try it~

**Comment by Fannxy** [comment]
I have succeed, thanks for your help (where c'1 should be -c1, as c2 + c3 = -c1 if [c] = 0).
I think i finally begin to understand the logic of the use of circuits in the ``BetaLibrary.cpp``, thanks again for your help!

**Comment by ladnir** [comment]
Glad it worked. Maybe should add this as a function. Don't think you're the first to ask for it.
