### ISSUE TITLE
Question about the experiment setting

### ISSUE THREAD

**Issue by sls33** [ladnir/aby3#43]
Greetings!

I have a question about the experiment setting in the paper "ABY3: A Mixed Protocol Framework for Machine Learning".

In section 6 Experiments (Experimental Setup), this paper says "Using the Linux tc command we consider two network settings: a LAN setting with a shared 10Gbps connection and sub-millisecond RTT latency and a WAN setting with a 40Mbps maximum throughput and 40ms RTT latency". Since in the Linux tc command, Mbps refers to MB/s, whether the WAN setting 40Mbps maximum throughput actually refers to 40MBps? 

We would very much appreciate it if you could answer this question.

**Comment by ladnir** [comment]
I assume it was actually Mbps. But who knows... That was a long time ago
