### ISSUE TITLE
undefined reference to ...

### ISSUE THREAD

**Issue by zhou-pz** [ladnir/aby3#46]
I linked all libraries in lib/ and thirdparty/unix/ while compiling my own program. but many 'undefined reference to' type error occur:

![image](https://user-images.githubusercontent.com/59403694/231116003-1267e037-e530-404d-8aa8-d70792e539fd.png)

what should i do next...

**Comment by ladnir** [comment]
a quick google would tell you the [answer](https://www.google.com/search?q=undefined+reference+to+pthread_join&client=firefox-b-1-d&sxsrf=APwXEdcEXKjVCMHVpe9jq6qASSm-nIL0Fw%3A1681231748424&ei=hI81ZMTEGZ_CkPIPlO-w2Ak&ved=0ahUKEwjElpmppKL-AhUfIUQIHZQ3DJsQ4dUDCA8&uact=5&oq=undefined+reference+to+pthread_join&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQAzIFCAAQgAQyBQgAEIAEMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgYIABAWEB4yCAgAEBYQHhAKMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeOgoIABBHENYEELADOgQIIxAnOgoIABCABBAUEIcCSgQIQRgAUJgTWLIZYKAbaAFwAXgAgAHRAogBowiSAQUyLTMuMZgBAKABAcgBCMABAQ&sclient=gws-wiz-serp)

add `-pthread` to the cmake `target_link_libraries(<yourLibraryName>  -pthread)`

**Comment by zhou-pz** [comment]
Thanks! the  **-pthread** option works. But other "undefined reference to" errors still remain:
![image](https://user-images.githubusercontent.com/59403694/231435058-756bf55e-ed21-47dd-ae49-8db104953268.png)

I try to add the "aby3/thirdparty/libOTe/cryptoTools/cryptoTools/Crypto/AES.cpp" file to compile together, but a "multiple definition" error occur:
![image](https://user-images.githubusercontent.com/59403694/231435996-96d067fd-9231-4ccc-a704-c5edcf72bf1b.png)

My program structure is:
![image](https://user-images.githubusercontent.com/59403694/231437337-d39c5a54-ef7a-41e3-b855-e1d253b4e989.png)
![image](https://user-images.githubusercontent.com/59403694/231437855-1bbb39b0-38ea-4685-bbd2-20e4ae11aca8.png)

I am not sure I use a right way to program upon aby3, do you have some advises for this?

**Comment by ladnir** [comment]
try
```
target_link_libraries(main 
   aby3_Tests
   com-psi_Tests
   aby3-ML
   com-psi
   aby3
   libOTe
   cryptoTools
   boost_atomic
   boost_filesystem
   boost_regex
   boost_thread
   boost_system
)
```

Oder of libraries can matter

**Comment by zhou-pz** [comment]
report the same errors
