### ISSUE TITLE
Bad address Error

### ISSUE THREAD

**Issue by Fannxy** [ladnir/aby3#47]
Dear ladnir,

I hope this message finds you well.  I have encountered an intermittent issue while running the program. This problem happens during multiple iterations, particularly during the evaluation of greater-than circuits, I occasionally receive the following error:

```bash
network send error: Bad address
at /root/aby3/thirdparty/libOTe/cryptoTools/cryptoTools/Network/Channel.cpp:871
```

This error seems to occur randomly and does not have a specific pattern. I have noticed it happening more frequently during circuit evaluations involving greater-than operations.

I would like to seek your guidance on how to address this issue. Are you aware of this problem, and do you have any suggestions or insights on how to avoid or mitigate it?

Any assistance or advice you can provide to help me resolve this issue would be greatly appreciated. I understand that you and the contributors may have limited time, and I am grateful for any attention you can give to this matter.

Best regards,
Fannxy

**Comment by Fannxy** [comment]
Plus, when the error comes, the program will continue with an extremely low resouce utilization... i think it may be blocked in somewhere, and the connection among the parties seems broken as i cannot see the connection in `iftop`.

**Comment by ladnir** [comment]
is this still an issue? missed it, sorry

**Comment by Fannxy** [comment]
It's been a while since the last time, and I think the issue may be related to my machine 233333. If I encounter any further problems, I will definitely reach out to you again. Thanks a lot!


-----Original Messages-----
From:"Peter Rindal" ***@***.***>
Send time:Wednesday, 01/10/2024 16:31:12
To: ladnir/aby3 ***@***.***>
Cc: "Xiaoyu Fan" ***@***.***>, Author ***@***.***>
Subject: Re: [ladnir/aby3] Bad address Error (Issue #47)






is this still an issue, missed it. sorry?
