### ISSUE TITLE
Some tests failed on Linux

### ISSUE THREAD

**Issue by vincehong** [ladnir/aby3#5]
Ubuntu 18.04 64 bit

# ./bin/frontend.exe -u
 0 - BtNetwork_Connect1_Test                   Passed   1ms
 1 - BtNetwork_RapidConnect_Test               Passed   56ms
 2 - BtNetwork_SocketInterface_Test            Passed   9ms
 3 - BtNetwork_OneMegabyteSend_Test            Passed   4ms
 4 - BtNetwork_ConnectMany_Test                Passed   11ms
 5 - BtNetwork_CrossConnect_Test               Passed   1ms
 6 - BtNetwork_ManySessions_Test               Passed   9ms
 7 - BtNetwork_bitVector_Test                  Passed   1ms
 8 - BtNetwork_AsyncConnect_Test               Passed   3ms
 9 - BtNetwork_std_Containers_Test             Passed   1ms
10 - BtNetwork_recvErrorHandler_Test           Passed   1ms
11 - BtNetwork_closeOnError_Test               Passed   2ms
12 - BtNetwork_AnonymousMode_Test              Passed   2ms
13 - BtNetwork_CancelChannel_Test              Passed   121ms
14 - BtNetwork_useAfterCancel_test             Passed   3ms
15 - BtNetwork_fastCancel                      Passed   28ms
16 - BtNetwork_ServerMode_Test                 Passed   39ms
17 - BtNetwork_clientClose_Test                Passed   56ms
18 - BtNetwork_BadConnect_Test                 Passed   1ms
19 - BtNetwork_oneWorker_Test                  Passed   0ms
20 - BtNetwork_queue_Test                      Passed   2ms
21 - wolfSSL_echoServer_test                   Skipped - ENABLE_WOLFSSL not defined   0ms
22 - wolfSSL_mutualAuth_test                   Skipped - ENABLE_WOLFSSL not defined   0ms
23 - wolfSSL_channel_test                      Skipped - ENABLE_WOLFSSL not defined   0ms
24 - wolfSSL_CancelChannel_Test                Skipped - ENABLE_WOLFSSL not defined   0ms
25 - AES                                       Passed   73ms
26 - BitVector_Indexing_Test                   Passed   0ms
27 - BitVector_Parity                          Passed   2ms
28 - BitVector_Append_Test                     Passed   0ms
29 - BitVector_Copy_Test                       Passed   0ms
30 - BitVector_Resize_Test                     Passed   0ms
31 - Ecc2mNumber_Test                          Skipped - ENABLE_MIRACL not defined.   0ms
32 - Ecc2mPoint_Test                           Skipped - ENABLE_MIRACL not defined.   0ms
33 - EccpNumber_Test                           Skipped - ENABLE_MIRACL not defined.   0ms
34 - EccpPoint_Test                            Skipped - ENABLE_MIRACL not defined.   0ms
35 - REccpNumber_Test                          Skipped - ENABLE_RELIC not defined.   0ms
36 - REccpPoint_Test                           Skipped - ENABLE_RELIC not defined.   0ms
37 - SBO_ptr_test                              Passed   0ms
38 - BetaCircuit_SequentialOp_Test             Passed   0ms
39 - BetaCircuit_int_Adder_Test                Passed   13ms
40 - BetaCircuit_int_Adder_const_Test          Passed   4ms
41 - BetaCircuit_int_Subtractor_Test           Passed   4ms
42 - BetaCircuit_int_Subtractor_const_Test     Passed   4ms
43 - BetaCircuit_uint_Adder_Test               Passed   4ms
44 - BetaCircuit_uint_Subtractor_Test          Passed   4ms
45 - BetaCircuit_int_Multiply_Test             Passed   0ms
46 - BetaCircuit_uint_Multiply_Test            Passed   0ms
47 - BetaCircuit_int_Divide_Test               Passed   5ms
48 - BetaCircuit_int_LessThan_Test             Passed   0ms
49 - BetaCircuit_int_GreaterThanEq_Test        Passed   0ms
50 - BetaCircuit_uint_LessThan_Test            Passed   0ms
51 - BetaCircuit_uint_GreaterThanEq_Test       Passed   0ms
52 - BetaCircuit_multiplex_Test                Passed   0ms
53 - BetaCircuit_negate_Test                   Passed   0ms
54 - BetaCircuit_bitInvert_Test                Passed   0ms
55 - BetaCircuit_removeSign_Test               Passed   0ms
56 - BetaCircuit_addSign_Test                  Passed   0ms
57 - BetaCircuit_json_Tests                    Skipped - USE_JSON not defined.   0ms
58 - BetaCircuit_bin_Tests                     Passed   4ms
59 - BetaCircuit_aes_test
  Passed   4ms
60 - BetaCircuit_int_Sh3Piecewise_Test         Passed   2ms
61 - Sh3_Runtime_schedule_test                 Passed   0ms
62 - Sh3_trim_test                             Passed   5ms
63 - Sh3_Encryptor_IO_test                     Passed   8ms
64 - Sh3_Encryptor_asyncIO_test                Passed   3ms
65 - Sh3_Evaluator_mul_test                  Failed - known issue. /root/aby3/aby3_tests/Sh3EvaluatorTests.cpp:515   0ms
66 - Sh3_Evaluator_asyncMul_test               Passed   26ms
67 - Sh3_Evaluator_truncationPai_test          Passed   1ms
68 - Sh3_Evaluator_asyncMul_fixed_test         Passed   2ms
69 - Sh3_Evaluator_asyncMul_matrixFixed_test   Passed   5ms
70 - SharedOT_eval_test                        Passed   3ms
71 - sh3_asyncArithBinMul_test                Passed   6ms
72 - sh3_asyncPubArithBinMul_test              Passed   2ms
73 - Sh3_f64_basics_test                       Passed   0ms
74 - Sh3_BinaryEngine_and_test                 Passed   285ms
75 - Sh3_BinaryEngine_add_test               mode: 2 failed at 1 251 != 219
mode: 2 failed at 2 43 != 11
mode: 2 failed at 3 227 != 195
mode: 2 failed at 4 123 != 91
mode: 2 failed at 5 149 != 181
mode: 2 failed at 7 86 != 118
mode: 2 failed at 10 73 != 105
mode: 2 failed at 11 145 != 177
mode: 2 failed at 13 106 != 74
mode: 2 failed at 15 47 != 15
mode: 2 failed at 18 22 != 54
mode: 2 failed at 22 30 != 62
mode: 2 failed at 23 223 != 255
mode: 2 failed at 24 189 != 157
mode: 2 failed at 25 88 != 120
mode: 2 failed at 26 115 != 83
mode: 2 failed at 27 220 != 252
mode: 2 failed at 29 205 != 237
mode: 2 failed at 30 130 != 162
mode: 2 failed at 31 132 != 164
mode: 2 failed at 38 40 != 8
mode: 2 failed at 39 76 != 108
mode: 2 failed at 43 118 != 86
mode: 2 failed at 44 236 != 204
mode: 2 failed at 45 252 != 220
mode: 2 failed at 47 94 != 126
mode: 2 failed at 50 196 != 228
mode: 2 failed at 51 248 != 216
mode: 2 failed at 56 81 != 113
mode: 2 failed at 57 64 != 96
mode: 2 failed at 58 211 != 243
mode: 2 failed at 62 91 != 123
mode: 2 failed at 63 98 != 66
mode: 2 failed at 64 190 != 158
mode: 2 failed at 65 4 != 36
mode: 2 failed at 66 26 != 58
mode: 2 failed at 71 204 != 236
mode: 2 failed at 72 68 != 100
mode: 2 failed at 73 215 != 247
mode: 2 failed at 77 96 != 64
mode: 2 failed at 79 239 != 207
mode: 2 failed at 80 178 != 146
mode: 2 failed at 84 248 != 216
mode: 2 failed at 86 128 != 160
mode: 2 failed at 88 15 != 47
mode: 2 failed at 89 41 != 9
mode: 2 failed at 91 7 != 39
mode: 2 failed at 93 19 != 51
mode: 2 failed at 94 27 != 59
mode: 2 failed at 95 173 != 141
mode: 2 failed at 102 227 != 195
mode: 2 failed at 103 22 != 54
mode: 2 failed at 104 84 != 116
mode: 2 failed at 107 25 != 57
mode: 2 failed at 110 63 != 31
mode: 2 failed at 115 211 != 243
mode: 2 failed at 116 202 != 234
mode: 2 failed at 119 106 != 74
mode: 2 failed at 120 198 != 230
mode: 2 failed at 122 21 != 53
mode: 2 failed at 124 138 != 170
mode: 2 failed at 125 175 != 143
Failed - /root/aby3/aby3_tests/Sh3BinaryEvaluatorTests.cpp:284   292ms
76 - Sh3_BinaryEngine_add_msb_test;            Passed   282ms
77 - Sh3_convert_b64Matrix_PackedBin_test      Passed   3ms
78 - Sh3_Piecewise_plain_test                  Passed   0ms
79 - Sh3_Piecewise_test                        Passed   16ms
80 - lowMC_Circuit_test             Passed   32ms
81 - lowMC_FileCircuit_test         Skipped - USE_JSON not defined   0ms
82 - lowMC_BinFileCircuit_test      Passed   15ms
83 - DB_computeKeys_test            Passed   13ms
84 - Perm3p_overwrite_Test          Passed   12ms
85 - Perm3p_additive_Test           Passed   1ms
86 - Perm3p_subset_Test             Passed   1ms
87 - switch_select_test             Passed   22ms
88 - switch_duplicate_test          Passed   42ms
89 - switch_full_test               Passed   85ms
90 - DB_cuckooHash_test             Passed   7ms
91 - DB_compare_test                Passed   15ms
92 - DB_Intersect_test              Passed   32ms
93 - DB_Intersect_sl_test           Passed   22ms
94 - DB_Intersect_ls_test           Passed   26ms
95 - DB_leftUnion_test              Passed   18ms

#############################################
           Failed (2)
           Passed (82)
            skipped (12)
#############################################

**Comment by ladnir** [comment]
I was able to reproduce. It seems to only sometimes occure. I'll investigate.

**Comment by ladnir** [comment]
This has been fixed.
