### ISSUE TITLE
Possible bugs of logistic statistics?

### ISSUE THREAD

**Issue by vincehong** [ladnir/aby3#6]
Suppose a batch of  10000 rows*100cols, each 64 bits, which is 8MB。
So it's 16MB at least for Replicated SS.

But the statistics is : N: 10000 D:100 B:10000 IT:1000 => 24.4529  iters/s  125.969 Mbps 
So there might be some bugs in the statistics?

**Comment by ladnir** [comment]
yeah not sure. Is it important that you get the numbers? Like are you benchmarking the code against something else? If so i could look into it...
