### ISSUE TITLE
Cannot open include file: 'boost/asio.hpp'

### ISSUE THREAD

**Issue by sandy9999** [ladnir/aby3#9]
I have followed the Windows Install Instructions until the cloning of function2. Now I have opened aby3.sln in Visual Studio 2019 but I get the error "Cannot open include file: 'boost/asio.hpp'" This is my directory structure

![image](https://user-images.githubusercontent.com/17477947/94541898-c41b2d80-0265-11eb-9c14-df5d66403f84.png)

I have followed through all the instructions to build libOTe and relic mentioned in the libOTe repository. However in this aby3 repository, considering that boost is installed in libOTe/cryptoTools/thirdparty/win , why is it looking for boost inside the aby3 repository?

**Comment by ladnir** [comment]
yeah... so libOTe looks for boost at either `c:\libs\boost` or at `.../libOTe/cryptoTools/thirdparty/win/boost`

But... aby3 only looks for it at  `c:\libs\boost`. So the simple fix is to move boost to this location. 

It also requires function2 and eigen to be at this location. 

In visual studio, you can see the includes paths by going looking at the Soltion Explorer, right click the project, properties-> C/C++ -> Additional Include Directories
